# Homework 1.1 for BAN6020 Data Management by Julia Reich on 09-14-2025

## Create DataFrame and Explore the Data

In [1]:
import pandas as pd

# Create DataFrame from EbayPcLaptopDataUnclean CSV data file
pc_df = pd.read_csv('EbayPcLaptopDataUnclean.csv')

In [2]:
# View first 20 rows of the data
pc_df.head(20)

,Item Number,Brand,Rating,Ratings Count,Processor,Screen Size,Manufacturer Color,Color,Ram Size,SSD Capacity,...,Release Year,Maximum Resolution,Model,OS,Hard Drive Capacity,Country Region Of Manufacture,Storage Type,Features,Condition,Seller Note
0,85264981001,CHUWI,NaN,NaN,Quad Core,14 in,NaN,Gray,8 GB,"1 Used, 1 support Max 1TB M.2 Extend",...,2021,2160 x 1440,CoreBook X,Windows 11 Home,512 GB SSD,China,SSD (Solid State Drive),"Backlit Keyboard, Built-in Microphone, Built...","New: A brand-new, unused, unopened, undamaged ...",NaN
1,85264981002,Dell,NaN,NaN,Intel Core i7 8th Gen.,14 in,NaN,Black,NaN,NaN,...,Refurbished in 2023,1920 x 1080,Dell Latitude 7490,Windows 11 Pro,2 TB,NaN,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - RefurbishedThe item shows minimal ...,“AAA PCs is a Microsoft Authorized Refurbisher...
2,85264981003,Dell,NaN,NaN,Intel Core i5-6300U,14 in,NaN,Black,16 GB,500 GB,...,2019,1920 x 1080,Dell Latitude E5470,Windows 10 Pro,500 GB,China,SSD (Solid State Drive),"10/100 LAN Card, Backlit Keyboard, Bluetooth, ...",UsedAn item that has been used previously. The...,"“Well kept, fully functional, includes battery..."
3,85264981004,HP,NaN,NaN,Intel Celeron N,11.6 in,NaN,Black,4 GB,NaN,...,NaN,1366 x 768,HP Chromebook 11 G6,Chrome OS,16 GB,NaN,eMMC,"Bluetooth, Built-in Microphone, Built-in Webca...",Good - RefurbishedThe item shows moderate wear...,“1-Year Allstate warranty. The original HP cha...
4,85264981005,Dell,NaN,NaN,Intel Core i5 6th Gen.,"Minimum 12.5""",NaN,NaN,8 GB,256 GB,...,2015,1366 x 768,Various Models,Windows 10,NO HDD,NaN,SSD (Solid State Drive),"10/100 LAN Card, Built-in Microphone, Built-in...",Good - RefurbishedThe item shows moderate wear...,“Laptops is tested & fully working with some s...
5,85264981006,Acer,4.5 out of 5 stars,193.0,Intel Celeron,11.6 in,Black,Black,4 GB,16 GB,...,2017,1366 x 768,Chromebook C738T-C44Z,Chrome OS,NaN,NaN,SSD (Solid State Drive),"Touchscreen, Bluetooth",NaN,NaN
6,85264981007,HP,4.5 out of 5 stars,23.0,Intel Celeron,11.6 in,NaN,Black,4 GB,16GB,...,2017,NaN,HP Chromebook 11 G5,Chrome OS,16 GB,NaN,SSD (Solid State Drive),"Bluetooth, Built-in Webcam",NaN,NaN
7,85264981008,Acer,5 out of 5 stars,20.0,Intel Celeron Dual-Core,11.6 inin,NaN,"Gray, Granite Gray",2GB,NaN,...,NaN,NaN,Chromebook C720-2848,Chrome OS,16GB,NaN,NaN,NaN,NaN,NaN
8,85264981009,Dell,NaN,NaN,i7 7th,14 in,NaN,Black,16 GB,500 GB,...,NaN,1920 x 1080,Dell Latitude 7480,win 11 pro,512 GB,NaN,SSD (Solid State Drive),Wi-Fi,Excellent - Refurbished: The item is in like-n...,NaN
9,85264981010,HP,5 out of 5 stars,5.0,Intel Core i3 10th Gen.,14 in,Mineral Silver,Silver,8 GB,64 GB,...,2020,1920 x 1080,Samsung Chromebook 3,Chrome OS,NaN,NaN,eMMC,"Touchscreen, Bluetooth, Built-in Webcam, Wi-Fi...",NaN,NaN
10,85264981011,Lenovo,NaN,NaN,"8350U, Core i5",14 in,NaN,Black,16 GB,128 GB,...,NaN,1920 x 1080,Lenovo T480,Windows 11 Pro,NaN,NaN,SSD (Solid State Drive),"Built-in Microphone, Built-in Webcam",UsedAn item that has been used previously. The...,"“Very good condition. very good performance, ..."
11,85264981012,Samsung,NaN,NaN,Intel Core i5 12th Gen.,13.3 in,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
12,85264981013,Acer,5 out of 5 stars,1.0,Intel Celeron N,11.6 in,Pure Silver,Silver,4 GB,32 GB,...,2020,1366 x 768,Acer Chromebook 311,Chrome OS,NaN,NaN,eMMC,Bluetooth,NaN,NaN
13,85264981014,Chuwi,NaN,NaN,Intel Celeron Processor N4100,14.1 in,NaN,Gray,8 GB,256 GB,...,2021,1920 x 1080,CHUWI Lapbook Pro,Windows 11 Home,256 GB,NaN,SSD (Solid State Drive),Wi-Fi,"New: A brand-new, unused, unopened, undamaged ...",NaN
14,85264981015,Chuwi,NaN,NaN,Intel Core i5-8259U,14 in,NaN,Gray,8 GB,512 GB,...,2021,2160 x 1440,CHUWI CoreBook X,Windows 10,512 GB,NaN,HDD + SSD,"Backlit Keyboard, Bluetooth, Built-in Micropho...","New: A brand-new, unused, unopened, undamaged ...",NaN
15,85264981016,Dell,NaN,NaN,Intel Core i5 7th Gen.,2 in,NaN,Black,8 GB,128 GB,...,NaN,1920 x 1080,Dell Latitude 5289,Windows 10 Pro,128 GB,NaN,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",UsedAn item that has been used previously. The...,“This dell computer was used before and will s...
16,85264981017,Dell,NaN,NaN,Intel Core i5 8th Gen.,15.6 in,NaN,Black,16 GB,512 GB,...,NaN,1920 x 1080,Dell Latitude E5500,Not Included,NaN,NaN,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Webcam, ...",UsedAn item that has been used previously. The...,“Good working used condition - wear marks from...
17,85264981018,Dell,NaN,NaN,Intel Celeron,11 in,NaN,Black,4 GB,128 GB,...,2019,1366 x 768,Dell Latitude 3189,Windows 10 Pro,128 GB,NaN,SSD (Solid State Drive),"Bluetooth, Built-in Microphone, Built-in Webca...",UsedAn item that has been used previously. The...,“Tested and guaranteed by certified dell lapto...
18,85264981019,Acer,NaN,NaN,Intel Celeron N,11.6 in,NaN,Gray,4 GB,16 GB,...,2018,1366 x 768,Acer Chromebook C731,Chrome OS,16 GB,NaN,SSD (Solid State Drive),"Bluetooth, Built-in Microphone, Built-in Web...",UsedAn item that has been used previously. The...,"“Acer Chromebook C731 in certified excellent, ..."
19,85264981020,Dell,NaN,NaN,Intel Core i7 8th Gen.,14 in,NaN,Black,NaN,NaN,...,Refurbished in 2023,1920 x 1080,Dell Latitude 7400,Windows 11 Pro,2 TB,NaN,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - RefurbishedThe item shows minimal ...,“AAA PCs is a Microsoft Authorized Refurbisher...

In [3]:
# View the last 20 rows of the data
pc_df.tail(20)

,Item Number,Brand,Rating,Ratings Count,Processor,Screen Size,Manufacturer Color,Color,Ram Size,SSD Capacity,...,Release Year,Maximum Resolution,Model,OS,Hard Drive Capacity,Country Region Of Manufacture,Storage Type,Features,Condition,Seller Note
6656,85264987601,Acer,NaN,NaN,Does not apply,Does not apply,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6657,85264987602,Dell,NaN,NaN,Intel Core i5 6th generation,"12, 5""",NaN,Black,NaN,120GB,...,NaN,Full HD,E7270,Windows 11 Pro,NO,NaN,NaN,"Touchscreen, 10/100 LAN Card, Bluetooth, Ba...",Used: An item that has been used previously. T...,NaN
6658,85264987603,Dell,NaN,NaN,Intel Core i5 4th generation,"14""",NaN,NaN,NaN,960GB,...,NaN,HD,E5440,Windows 11 Pro,NO,NaN,NaN,"10/100 LAN Card, Wi-Fi, SD Card Reader",Used: An item that has been used previously. T...,NaN
6659,85264987604,AUO,NaN,NaN,Does not apply,Does not apply,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6660,85264987605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6661,85264987606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6662,85264987607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6663,85264987608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6664,85264987609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6665,85264987610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6666,85264987611,Dell,NaN,NaN,Intel Core i5 4th generation,"14""",NaN,NaN,NaN,960GB,...,NaN,HD,E5440,Windows 11 Pro,NO,NaN,NaN,NaN,Used: An item that has been used previously. T...,NaN
6667,85264987612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6668,85264987613,HP,NaN,NaN,Does not apply,Does not apply,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6669,85264987614,AUO,NaN,NaN,Does not apply,Does not apply,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6670,85264987615,Apple,NaN,NaN,Does not apply,Does not apply,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6671,85264987616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6672,85264987617,NaN,NaN,NaN,NaN,NaN,NaN,Negro,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller refurbished: The item has been restored...,NaN
6673,85264987618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN
6674,85264987619,Lenovo,NaN,NaN,NaN,NaN,NaN,Black,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6675,85264987620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN

In [4]:
# Import EbayLaptopPriceData CSV, convert to a DataFrame, and 
#    preview it before merging it with our original DataFrame
pc_price_df = pd.read_csv('EbayPcLaptopPriceData.csv')
pc_price_df

      Item Number               Price
0     85264981001            $303.68
1     85264981002  $399.99 to $634.99
2     85264981003            $175.00
3     85264981004             $84.99
4     85264981005            $101.22
...           ...                 ...
6671  85264987616            $108.06
6672  85264987617          $2,108.99
6673  85264987618            $105.86
6674  85264987619            $567.74
6675  85264987620             $89.28

[6676 rows x 2 columns]

In [5]:
# Merge existing PC DataFrame with Laptop Price DataFrame using Item Number
pc_df = pd.merge(pc_df, pc_price_df, on='Item Number', how='left')
pc_df

,Item Number,Brand,Rating,Ratings Count,Processor,Screen Size,Manufacturer Color,Color,Ram Size,SSD Capacity,...,Maximum Resolution,Model,OS,Hard Drive Capacity,Country Region Of Manufacture,Storage Type,Features,Condition,Seller Note,Price
0,85264981001,CHUWI,NaN,NaN,Quad Core,14 in,NaN,Gray,8 GB,"1 Used, 1 support Max 1TB M.2 Extend",...,2160 x 1440,CoreBook X,Windows 11 Home,512 GB SSD,China,SSD (Solid State Drive),"Backlit Keyboard, Built-in Microphone, Built...","New: A brand-new, unused, unopened, undamaged ...",NaN,$303.68
1,85264981002,Dell,NaN,NaN,Intel Core i7 8th Gen.,14 in,NaN,Black,NaN,NaN,...,1920 x 1080,Dell Latitude 7490,Windows 11 Pro,2 TB,NaN,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - RefurbishedThe item shows minimal ...,“AAA PCs is a Microsoft Authorized Refurbisher...,$399.99 to $634.99
2,85264981003,Dell,NaN,NaN,Intel Core i5-6300U,14 in,NaN,Black,16 GB,500 GB,...,1920 x 1080,Dell Latitude E5470,Windows 10 Pro,500 GB,China,SSD (Solid State Drive),"10/100 LAN Card, Backlit Keyboard, Bluetooth, ...",UsedAn item that has been used previously. The...,"“Well kept, fully functional, includes battery...",$175.00
3,85264981004,HP,NaN,NaN,Intel Celeron N,11.6 in,NaN,Black,4 GB,NaN,...,1366 x 768,HP Chromebook 11 G6,Chrome OS,16 GB,NaN,eMMC,"Bluetooth, Built-in Microphone, Built-in Webca...",Good - RefurbishedThe item shows moderate wear...,“1-Year Allstate warranty. The original HP cha...,$84.99
4,85264981005,Dell,NaN,NaN,Intel Core i5 6th Gen.,"Minimum 12.5""",NaN,NaN,8 GB,256 GB,...,1366 x 768,Various Models,Windows 10,NO HDD,NaN,SSD (Solid State Drive),"10/100 LAN Card, Built-in Microphone, Built-in...",Good - RefurbishedThe item shows moderate wear...,“Laptops is tested & fully working with some s...,$101.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6843,85264987616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN,$108.06
6844,85264987617,NaN,NaN,NaN,NaN,NaN,NaN,Negro,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller refurbished: The item has been restored...,NaN,"$2,108.99"
6845,85264987618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN,$105.86
6846,85264987619,Lenovo,NaN,NaN,NaN,NaN,NaN,Black,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$567.74
6847,85264987620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"New: A brand-new, unused, unopened, undamaged ...",NaN,$89.28

In [6]:
# View list of columns (predictors) and their datatypes
pc_df.dtypes

Item Number                        int64
Brand                             object
Rating                            object
Ratings Count                    float64
Processor                         object
Screen Size                       object
Manufacturer Color                object
Color                             object
Ram Size                          object
SSD Capacity                      object
GPU                               object
Processor Speed                   object
Type                              object
Release Year                      object
Maximum Resolution                object
Model                             object
OS                                object
Hard Drive Capacity               object
Country Region Of Manufacture     object
Storage Type                      object
Features                          object
Condition                         object
Seller Note                       object
Price                             object
dtype: object

In [7]:
# Find how many missing values (% of all) in each column of the DataFrame
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number                       0.00
Brand                            37.70
Rating                           95.60
Ratings Count                    95.60
Processor                        40.52
Screen Size                      39.71
Manufacturer Color               97.08
Color                            66.49
Ram Size                         66.49
SSD Capacity                     56.45
GPU                              53.01
Processor Speed                  58.37
Type                             49.08
Release Year                     87.32
Maximum Resolution               61.40
Model                            50.95
OS                               52.70
Hard Drive Capacity              63.96
Country Region Of Manufacture    96.95
Storage Type                     62.60
Features                         61.00
Condition                         9.43
Seller Note                      76.99
Price                             0.00
dtype: float64

In [8]:
# Any column with Missingness that comprises more than 95% of the rows in the dataset will be removed.
#   If more than 95% of a column's data is missing, the column has almost no data to analyze or train on
# I have chosen to delete these columns with overtly high missingness, as it will not lead to much substance for further analysis
#   For example, imputation at this level is likely unsound; it introduces bias and can distort analysis
# A note in the appendix or in the Methods section will suffice as documentation of the removal of such columns

pc_df = pc_df.drop(columns = ['Rating','Ratings Count','Manufacturer Color','Country Region Of Manufacture'])

# Check work
pc_df.head(5)

,Item Number,Brand,Processor,Screen Size,Color,Ram Size,SSD Capacity,GPU,Processor Speed,Type,Release Year,Maximum Resolution,Model,OS,Hard Drive Capacity,Storage Type,Features,Condition,Seller Note,Price
0,85264981001,CHUWI,Quad Core,14 in,Gray,8 GB,"1 Used, 1 support Max 1TB M.2 Extend",Intel Iris Plus Graphics 655,Max up to 3.80 GHz,Notebook/Laptop,2021,2160 x 1440,CoreBook X,Windows 11 Home,512 GB SSD,SSD (Solid State Drive),"Backlit Keyboard, Built-in Microphone, Built...","New: A brand-new, unused, unopened, undamaged ...",NaN,$303.68
1,85264981002,Dell,Intel Core i7 8th Gen.,14 in,Black,NaN,NaN,Intel UHD Graphics 620,4.20 GHz (1.90 GHz Base Frequency),Notebook/Laptop,Refurbished in 2023,1920 x 1080,Dell Latitude 7490,Windows 11 Pro,2 TB,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - RefurbishedThe item shows minimal ...,“AAA PCs is a Microsoft Authorized Refurbisher...,$399.99 to $634.99
2,85264981003,Dell,Intel Core i5-6300U,14 in,Black,16 GB,500 GB,Intel HD Graphics,2.40 GHz,Notebook/Laptop,2019,1920 x 1080,Dell Latitude E5470,Windows 10 Pro,500 GB,SSD (Solid State Drive),"10/100 LAN Card, Backlit Keyboard, Bluetooth, ...",UsedAn item that has been used previously. The...,"“Well kept, fully functional, includes battery...",$175.00
3,85264981004,HP,Intel Celeron N,11.6 in,Black,4 GB,NaN,Intel HD Graphics 500,2.40 GHz,Notebook/Laptop,NaN,1366 x 768,HP Chromebook 11 G6,Chrome OS,16 GB,eMMC,"Bluetooth, Built-in Microphone, Built-in Webca...",Good - RefurbishedThe item shows moderate wear...,“1-Year Allstate warranty. The original HP cha...,$84.99
4,85264981005,Dell,Intel Core i5 6th Gen.,"Minimum 12.5""",NaN,8 GB,256 GB,Integrated,Minimum 1.40 GHz,Notebook/Laptop,2015,1366 x 768,Various Models,Windows 10,NO HDD,SSD (Solid State Drive),"10/100 LAN Card, Built-in Microphone, Built-in...",Good - RefurbishedThe item shows moderate wear...,“Laptops is tested & fully working with some s...,$101.22

In [9]:
# Check DataFrame shape
# Columns should diminish from 24 to 20
pc_df.shape

(6848, 20)

In [10]:
# Test whether dropping all rows with missing values will be beneficial for analysis
# drop records with missing values and assign results to new dataframe
pc_df_none_missing = pc_df.dropna()
pc_df_none_missing

,Item Number,Brand,Processor,Screen Size,Color,Ram Size,SSD Capacity,GPU,Processor Speed,Type,Release Year,Maximum Resolution,Model,OS,Hard Drive Capacity,Storage Type,Features,Condition,Seller Note,Price
2,85264981003,Dell,Intel Core i5-6300U,14 in,Black,16 GB,500 GB,Intel HD Graphics,2.40 GHz,Notebook/Laptop,2019,1920 x 1080,Dell Latitude E5470,Windows 10 Pro,500 GB,SSD (Solid State Drive),"10/100 LAN Card, Backlit Keyboard, Bluetooth, ...",UsedAn item that has been used previously. The...,"“Well kept, fully functional, includes battery...",$175.00
17,85264981018,Dell,Intel Celeron,11 in,Black,4 GB,128 GB,Intel UHD Graphics 600,1.10 GHz,Notebook/Laptop,2019,1366 x 768,Dell Latitude 3189,Windows 10 Pro,128 GB,SSD (Solid State Drive),"Bluetooth, Built-in Microphone, Built-in Webca...",UsedAn item that has been used previously. The...,“Tested and guaranteed by certified dell lapto...,$129.99
18,85264981019,Acer,Intel Celeron N,11.6 in,Gray,4 GB,16 GB,Intel HD Graphics,1.60 GHz,Notebook/Laptop,2018,1366 x 768,Acer Chromebook C731,Chrome OS,16 GB,SSD (Solid State Drive),"Bluetooth, Built-in Microphone, Built-in Web...",UsedAn item that has been used previously. The...,"“Acer Chromebook C731 in certified excellent, ...",$39.99
22,85264981023,Dell,Intel Core i5 6th Gen.,12.5 in,Black,8 GB,256 GB,Intel HD Graphics,2.60 GHz,Notebook/Laptop,2013,1920 x 1080,Dell Latitude 5289,Windows 10,256 GB,SSD (Solid State Drive),"Bluetooth, Built-in Microphone, Built-in Webcam",UsedAn item that has been used previously. The...,“This dell computer was used before and will s...,$199.99
29,85264981030,Dell,Intel Core i5 7th Gen.,15.6 in,Black,16 GB,512 GB,Intel HD Graphics 620,3.10 GHz (2.50 GHz Base Frequnecy),Notebook/Laptop,Refurbished in 2023,1920 x 1080,Dell Latitude 5580,Windows 10 Pro,512 GB,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - RefurbishedThe item shows minimal ...,“The item shows minimal wear and is backed by ...,$344.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819,85264986610,Lenovo,Intel Core i7 8th Gen.,14 in,Black,16 GB,256 GB,Intel HD Graphics 620,1.90 GHz,Notebook/Laptop,2018,1920 x 1080,Lenovo T480,Windows 11,16 GB,SSD (Solid State Drive),"Bluetooth, Built-in Microphone, Built-in Web...",UsedAn item that has been used previously. The...,“most of them have good to excellent cosmetic ...,$225.00
6309,85264987100,HP,AMD Ryzen 7 7840HS,16.1 in,Black,16 GB,512 GB,NVIDIA GeForce RTX 4060,5.10 ghz,Notebook/Laptop,2023,1920 x 1080,HP Omen,Windows 11 Home,Not Applicable,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Certified - RefurbishedThe item is in pristine...,“Factory certified refurbished item in HP seal...,$949.47
6314,85264987105,Microsoft,Intel Pentium Gold,10.5 in,Silver,64 GB,64 GB,Intel UHD Graphics 615,1.10 GHz,Notebook/Laptop,2021,1920 x 1280,Microsoft Surface Go 3,Windows 11 Home S,64 GB,SSD (Solid State Drive),"Touchscreen, Bluetooth, Wi-Fi",UsedAn item that has been used previously. The...,“very good condition. Fully tested and factory...,$124.00
6332,85264987123,Acer,Intel Celeron N,11.6 in,Gray,4 GB,32GB,Intel HD Graphics 400,2.48 GHz,Notebook/Laptop,2017,1366 x 768,C731T-C0X8,Chrome OS,32 GB,eMMC,Touchscreen,UsedAn item that has been used previously. The...,“ITEM is Fully Tested & Functional Item MAY co...,$41.00
6334,85264987125,Lenovo,Intel Core i3 12th Gen.,15.6 in,Gray,8 GB,256 GB,Intel UHD Graphics,1.20 GHz,Notebook/Laptop,2022,1920 x 1080,Lenovo IdeaPad 3 15IAU7,Windows 11 Home,8 GB,SSD (Solid State Drive),Built-in Webcam,"Open boxAn item in excellent, new condition wi...",“100% Functional! In Great Condition! A few sm...,$192.00 to $203.05

In [11]:
# When we drop all rows with missing values, the remaining dataset results in only 2% of the original dataset.
# Since this yields such a low amount of remaining rows, dropping all rows with missing values
# will not be informative for analysis; we lose too much data to support committing to this step.
print(round(139/6848*100,4))

# Therefore, I continue with the pc_df original copy below.
# In the following section of code, I begin to dive into tbe details of each column
# Begin with Brand column, the first column in our PC dataset

2.0298

## Standardize and Clean Values in Columns

### Brand column

In [12]:
# get list of unique values for Brand column
brand_unique_values = pc_df['Brand'].unique()
print(f"There are {len(brand_unique_values)} unique Brand values: {brand_unique_values}")

There are 135 unique Brand values: ['CHUWI' 'Dell' 'HP' 'Acer' 'Lenovo' 'Samsung' 'Chuwi' nan 'Microsoft'
 'LG' 'Toshiba' 'SGIN' 'Panasonic' 'ASUS' 'Olpc' 'Mouse Computer' 'AUUSDA'
 'Apple' 'Fujitsu Siemens' 'Fujitsu' 'AUO' 'KODAK' 'LCD Replacement'
 'Packard Bell' 'Intel' 'Olidata' 'IVO' 'JVC' 'Unbranded' 'Simpletek'
 'ChiMei INNOLUX' 'INNOLUX' 'Getac' 'DELL' 'Google' 'HW13WX001' 'Compaq'
 'Casio' 'ChiMei' 'HannStar' 'Delta' 'Hyundai' '?' 'FEC' 'AU Optronics'
 'Chunghwa' 'CLAA156WA13A' 'Alienware' 'VAIO' 'Sony' 'Does not apply'
 'C600' 'CLAA156WA11A' 'Chimei INNOLUX' 'VECTOR' 'LiteON' 'CHUNGWA'
 'Kodak' 'Uniwill' 'Asem' 'InnoLux' 'HP DELL LENOVO SELECT FROM ABOVE'
 'Zebra' 'Geo' 'MSI' 'Gateway' 'dell' 'Fujitsu PC Corp.' 'Asus' 'HiDes'
 'GPD' 'XPLORE' 'Craig' 'PANASONIC' 'Huawei' 'Metabox' 'Different'
 'Orbitkey' 'Kano' 'IBM' 'See Title/Description' 'Jumper' 'Media Wave'
 'Durabook' 'Not Applicable' 'GIGABYTE' 'DELL/HP/LENOVO/Fujitsu/Toshiba'
 'LENOVO' 'Razer' 'Lenova' 'GETAC' 'Fusion5' 'Dell Inc.' 'AMIAMO'
 'Packard bell' 'Lenovo T530' 'Dell 16gb' 'ProBook' 'AIRBAR' 'Zzetze'
 'Motion Computing' 'GoldBook' 'Dell Inspiron' 'Insignia' 'Universal'
 'Dell Latitude' 'Unbranded/Generic' 'CLEVO' 'Major Brand' 'ACER'
 'CLAA116WA03A' 'Shed Number 2' 'www.TAG1000Diver.com' 'nevada' 'Olympus'
 'Chingwa' 'Apple / LG' 'HannnStar' 'Fuji' 'Sony VAIO' 'Delta / DELL'
 'Lenovo T440' 'Dell Latitude 7275' 'Mixt' 'GERICOM' 'Top Performance'
 'MEDION' 'CHUNGHWA' 'Vulcan Electronics' 'Frontier'
 'Dell/HP/Lenovo/Stone' 'SCSI' 'xnote' 'Acer / IOmega' 'Bormann']

In [13]:
# Replace null values with 'Unknown'
pc_df['Brand'] = pc_df['Brand'].fillna("Unknown")
# Check work
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor              40.52
Screen Size            39.71
Color                  66.49
Ram Size               66.49
SSD Capacity           56.45
GPU                    53.01
Processor Speed        58.37
Type                   49.08
Release Year           87.32
Maximum Resolution     61.40
Model                  50.95
OS                     52.70
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note            76.99
Price                   0.00
dtype: float64

In [14]:
# Use ChatGPT to create a valid brands dictionary that maps credible brands to current values in Series, and a junk brands dictionary to identify non-brand names
# Citation: ChatGPT. (2025, September 11). Conversation with ChatGPT about credible PC brands and Python dictionaries. OpenAI. Personal communication.

pc_brands_dictionary = {
    # Acer family
    "ACER": "Acer", "Acer": "Acer", "Acer / IOmega": "Acer",
    # Alienware
    "Alienware": "Alienware",
    # Apple
    "Apple": "Apple", "Apple / LG": "Apple",
    # Asus
    "ASUS": "Asus", "Asus": "Asus",
    # Dell family
    "DELL": "Dell", "Dell": "Dell", "Dell Inc.": "Dell",
    "Dell Inspiron": "Dell", "Dell Latitude": "Dell", "Dell Latitude 7275": "Dell", "dell": "Dell",
    # Lenovo family
    "LENOVO": "Lenovo", "Lenovo": "Lenovo", "Lenova": "Lenovo",
    "Lenovo T440": "Lenovo", "Lenovo T530": "Lenovo",
    # LG family
    "LG": "LG", "xnote": "LG",
    # Sony/VAIO
    "Sony": "Sony", "Sony VAIO": "VAIO", "VAIO": "VAIO",
    # Panasonic
    "PANASONIC": "Panasonic", "Panasonic": "Panasonic",
    # Packard Bell
    "Packard Bell": "Packard Bell", "Packard bell": "Packard Bell",
    # Kodak
    "KODAK": "Kodak", "Kodak": "Kodak",
    # Fujitsu
    "Fujitsu": "Fujitsu", "Fujitsu PC Corp.": "Fujitsu", "Fujitsu Siemens": "Fujitsu",
    # Getac
    "GETAC": "Getac", "Getac": "Getac",
    # others (unique)
    "CHUWI": "Chuwi", "Chuwi": "Chuwi", "CLEVO": "Clevo", "Compaq": "Compaq", "Craig": "Craig",
    "Durabook": "Durabook", "Fusion5": "Fusion5", "GERICOM": "Gericom", "GIGABYTE": "Gigabyte",
    "Gateway": "Gateway", "Geo": "Geo", "GoldBook": "GoldBook", "Google": "Google", "HP": "HP",
    "Huawei": "Huawei", "Hyundai": "Hyundai", "IBM": "IBM", "Insignia": "Insignia", "Intel": "Intel",
    "Jumper": "Jumper", "Kano": "Kano", "MEDION": "Medion", "MSI": "MSI", "Metabox": "Metabox",
    "Microsoft": "Microsoft", "Motion Computing": "Motion Computing", "Mouse Computer": "Mouse Computer",
    "Olidata": "Olidata", "Olpc": "OLPC", "Razer": "Razer", "Samsung": "Samsung", "SGIN": "SGIN",
    "Simpletek": "Simpletek", "Toshiba": "Toshiba", "Uniwill": "Uniwill", "VECTOR": "Vector",
    "Vulcan Electronics": "Vulcan Electronics", "XPLORE": "Xplore", "Zebra": "Zebra"
}

In [15]:
# Standardize valid brand names
for brand in pc_brands_dictionary:
    # replace each brand value with true brand name in dictionary
    pc_df['Brand'].replace(brand, pc_brands_dictionary[brand], inplace=True)

C:\Users\jemre\AppData\Local\Temp\ipykernel_20072\1253639198.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pc_df['Brand'].replace(brand, pc_brands_dictionary[brand], inplace=True)

In [16]:
# Check work
brand_unique_values = pc_df['Brand'].unique()
print(f"There are {len(brand_unique_values)} unique Brand values: {brand_unique_values}")

There are 112 unique Brand values: ['Chuwi' 'Dell' 'HP' 'Acer' 'Lenovo' 'Samsung' 'Unknown' 'Microsoft' 'LG'
 'Toshiba' 'SGIN' 'Panasonic' 'Asus' 'OLPC' 'Mouse Computer' 'AUUSDA'
 'Apple' 'Fujitsu' 'AUO' 'Kodak' 'LCD Replacement' 'Packard Bell' 'Intel'
 'Olidata' 'IVO' 'JVC' 'Unbranded' 'Simpletek' 'ChiMei INNOLUX' 'INNOLUX'
 'Getac' 'Google' 'HW13WX001' 'Compaq' 'Casio' 'ChiMei' 'HannStar' 'Delta'
 'Hyundai' '?' 'FEC' 'AU Optronics' 'Chunghwa' 'CLAA156WA13A' 'Alienware'
 'VAIO' 'Sony' 'Does not apply' 'C600' 'CLAA156WA11A' 'Chimei INNOLUX'
 'Vector' 'LiteON' 'CHUNGWA' 'Uniwill' 'Asem' 'InnoLux'
 'HP DELL LENOVO SELECT FROM ABOVE' 'Zebra' 'Geo' 'MSI' 'Gateway' 'HiDes'
 'GPD' 'Xplore' 'Craig' 'Huawei' 'Metabox' 'Different' 'Orbitkey' 'Kano'
 'IBM' 'See Title/Description' 'Jumper' 'Media Wave' 'Durabook'
 'Not Applicable' 'Gigabyte' 'DELL/HP/LENOVO/Fujitsu/Toshiba' 'Razer'
 'Fusion5' 'AMIAMO' 'Dell 16gb' 'ProBook' 'AIRBAR' 'Zzetze'
 'Motion Computing' 'GoldBook' 'Insignia' 'Universal' 'Unbranded/Generic'
 'Clevo' 'Major Brand' 'CLAA116WA03A' 'Shed Number 2'
 'www.TAG1000Diver.com' 'nevada' 'Olympus' 'Chingwa' 'HannnStar' 'Fuji'
 'Delta / DELL' 'Mixt' 'Gericom' 'Top Performance' 'Medion' 'CHUNGHWA'
 'Vulcan Electronics' 'Frontier' 'Dell/HP/Lenovo/Stone' 'SCSI' 'Bormann']

In [17]:
# replace each junk brand value with 'Unknown' value
for entry in brand_unique_values:
    if entry not in pc_brands_dictionary:
        pc_df['Brand'].replace(entry, 'Unknown', inplace=True)

C:\Users\jemre\AppData\Local\Temp\ipykernel_20072\4026111950.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pc_df['Brand'].replace(entry, 'Unknown', inplace=True)

In [19]:
# Check work
brand_unique_values = pc_df['Brand'].unique()
brand_unique_values.sort()
print(f"There are {len(brand_unique_values)} unique Brand values: {brand_unique_values}")

There are 46 unique Brand values: ['Acer' 'Alienware' 'Apple' 'Asus' 'Chuwi' 'Compaq' 'Craig' 'Dell'
 'Durabook' 'Fujitsu' 'Fusion5' 'Gateway' 'Geo' 'Getac' 'GoldBook'
 'Google' 'HP' 'Huawei' 'Hyundai' 'IBM' 'Insignia' 'Intel' 'Jumper' 'Kano'
 'Kodak' 'LG' 'Lenovo' 'MSI' 'Metabox' 'Microsoft' 'Motion Computing'
 'Mouse Computer' 'Olidata' 'Packard Bell' 'Panasonic' 'Razer' 'SGIN'
 'Samsung' 'Simpletek' 'Sony' 'Toshiba' 'Uniwill' 'Unknown' 'VAIO'
 'Vulcan Electronics' 'Zebra']

### Processor column

In [20]:
# get list of unique values for Processor column
processor_unique_values = pc_df['Processor'].unique()
print(f"There are {len(processor_unique_values)} unique Processor values: {processor_unique_values}")

There are 462 unique Processor values: ['Quad Core' 'Intel Core i7 8th Gen.' 'Intel Core i5-6300U'
 'Intel Celeron N' 'Intel Core i5 6th Gen.' 'Intel Celeron'
 'Intel Celeron Dual-Core' 'i7 7th' 'Intel Core i3 10th Gen.'
 '8350U,  Core i5' 'Intel Core i5 12th Gen.'
 'Intel Celeron Processor N4100' 'Intel Core i5-8259U'
 'Intel Core i5 7th Gen.' 'Intel Core i5 8th Gen.'
 'Intel Core i7 13th Gen.' 'AMD Ryzen 5' nan 'i5-8365U'
 'Intel Core i5 4th Gen.' 'Intel Core i5-1135G7' 'Intel Celeron N3160'
 'i5-7200U' 'Intel Celeron N4100' 'Intel Core i7 12th Gen.'
 'Intel Core i5-4300U' 'i7-7820HQ' 'Intel Core i5-4200U'
 'Intel Celeron N5100' 'Intel Core i5-8250U' 'Intel Core i7 13th Gen'
 'Intel Core i3 6th Gen.' 'Intel i5' 'Intel Core i5' 'AMD A4 Dual-Core'
 'Intel Core i7 6th Gen.' 'Does Not Apply' 'Intel Core i5 2nd Gen.'
 'NVIDIA Tegra 3' 'i5-7300HQ' 'Core i7' 'Intel Core i3-6100U'
 'Intel i7-Q740 1.73GHz' 'Intel Core i7' 'Intel Core i5-3320M'
 'Intel Core i5 11th Gen.' 'MediaTek MT8183' 'Intel Core i5 13th Gen.'
 'Intel Core i5 10th Gen.' 'Intel Core i5 6th Gen' 'Intel Core i5-8265U'
 'Intel Core i3 11th Gen.' 'Intel Core i5-10310u' 'Intel Core i7 4th Gen.'
 'unknown' 'AMD Ryzen 3Pro' 'Celeron N2930' 'Intel Core i7 7th Gen.'
 'Does not apply' 'Intel Core i5 4th generation' 'Intel Core 2 Duo'
 '8250U' 'Intel Core i3 12th Gen.' 'ntel,' 'Intel Core i5 6th generation'
 'Intel Core M-5Y71' 'Intel Core i3 2330M' 'Intel Pentium' 'Intel'
 'Intel Core i5 3rd generation' 'Intel Core i3 4th generation'
 'Intel Core I5-2520M' 'Intel Core i3 7th generation' 'Intel i5-5300U'
 '8365U' 'Intel Core i3 6th generation' 'Intel Core i5 5th generation'
 '12th Gen Intel Core i5-12450H' 'pentium4' 'Intel Core i7 11th Gen.'
 'amd 3020e' '8265U' 'Intel Core i5 7th generation' 'inter Core i7 8550U'
 'Intel Core I5 \u200b\u200b12th Generation'
 'Intel Core i3 10th generation' 'i5-6300 2.4 GHz'
 'Intel Core i5 2nd generation' 'AMD Ryzen 5 7000 Series'
 'Intel Core i5 9th Gen.' 'i5' 'Intel Core i5-5300U'
 'Intel Core i3 3rd Gen.' 'A9 chip' 'Intel Atom Quad-Core' 'Intel Xeon'
 'Intel Core i7 2nd Gen.' 'Intel Core i7 9th Gen.' 'Google Tensor G2'
 'Intel Core i7-7600U' 'Core i5-7300U' 'Qualcomm MSM8909'
 'Core i5 8th gen i5-8365U' 'i7-8550U' 'AMD Ryzen 7' 'ntel' '?'
 'intel Core m5' 'Intel Pentium 4 M' 'Intel Core i7 7th Gen' '^?'
 'Core i5 5300U 2.30 GHz' 'Intel Core i3 8th generation'
 'Intel Core i7 10th Gen.' 'i9-13900HX' 'Intel Core i9 13th Gen.'
 'Intel Core I5-7200U' 'Intel Core i5 3rd Gen.' 'Intel Core i5-8365U'
 'Unknown' 'Intel Core i5 5th Gen.' 'Intel Core i7 8th generation'
 'Intel Core i7 11th Generation' 'V19' 'I5-4250U' 'I5'
 'inter Core i5 8250U' 'Intel Core i7 6th generation'
 'Intel Core i5 4th Gen' 'Core i5 6300U 2.40GHz'
 'Intel Core i5-6300U (6th Gen)' 'Intel Core i3 4th Gen.'
 'Intel Pentium Gold processor 4415Y' 'i5-4200m' 'i5-6300u'
 'Intel Core i7-8665U' 'Intel Core i3 2nd Gen.' 'Intel Celeron N3350'
 'AMD A6 Dual-Core' 'AMD'
 'Intel Core i5 6TH TILL 12TH GEN SELECT FROM ABOVE'
 'INTEL CORE i7 6th gen' 'No' 'Intel Core i7-8550U' 'AMD A4-9120C'
 'Amd A4-9120c Radeon R4 Dual-Core' 'AMD Ryzen 3 4000 Series'
 'Intel Core i5-4300Y' 'Intel Core i5 1st Gen.' 'AMD Ryzen 3'
 'Intel Core i7-1065G7' 'Microsoft SQ2' 'Intel® Core™ i5 i5-3210M'
 'Intel® Core™ i5 i5-2520M' 'Samsung Exynos 5 Dual' 'Intel I7-10610u'
 'Intel Core m3 7th Gen.' 'Intel i5-2467M' 'Intel Core i3 8th Gen.'
 'core i5 8th gen' 'AMD Athlon Gold 3150U 3.30GHz' 'AMD A4' 'AMD Athlon'
 'Intel Core M5' 'Unspecified' 'Intel Core i5-7300U 7th Gen.'
 'AMD Ryzen 7 Pro 3700U' 'i5-8350U' 'Intel Core i7-6600U @ 2.6GHz'
 'Intel Core i7 3rd Gen.' 'Intel Core I5-13420H'
 'Intel Core i5 vPro 8th Gen' 'Intel Core m5 6th Gen.'
 'Intel Atom Single-Core' 'Intel Core i3-1115G4'
 'Intel Pentium 3825U 1.90GHz' 'AMD Ryzen 7 7840HS' 'Intel i7-1265U'
 'Intel Core i7 8th Gen' 'Qualcomm Snapdragon 7c Gen 2'
 'Intel Quad i7-6920HQ @2.90GHz' 'Intel Core i5-8350U' 'intel N100'
 'Intel Core i5-5300U CPU @ 2.30 GHz' 'i5-11500H'
 'Qualcomm Snapdragon 8cx Gen 2' 'Mediatek' 'AMD Ryzen 7 7000 Series'
 'Intel Atom Dual-Core' 'Intel Core i7-8665U Quad-Core 1.9GHz'
 'Intel Pentium Silver N6000' 'Intel Core i3 7th Gen.'
 'Intel Celeron N2840' 'Intel Core 2 Quad' 'Intel Core i7-13700H'
 'Intel Pentium Gold' 'Intel Celeron N4020' 'MediaTek MT8173C'
 'i5 3rd Gen' 'i5-10210U' '10th Gen Intel Core i5' 'Intel Core i7-1185G7'
 'Intel Core i3' 'Arm Cortex-A Series' 'INTEL I5 2nd GEN.'
 'Intel Celeron N3050' 'Intel Pentium M' 'Intel Celeron N4500'
 'Intel Core i7-1355U' 'Android 4.0' 'INTEL CORE i7' 'Intel Core i5-4310U'
 'Core i5-5300U 2.30GHz' '11th Gen Intel Core i5-1135G7'
 'Intel Core i7 1st Gen.' '11 Gen intel Core i3' 'Intel Core i7-1265U'
 'E3-1505M v6' 'Intel® Core™ i7 i7-6500U' 'FZ-G1'
 'Intel i7-8665U QuadCore 8th Gen' 'AMD Ryzen 5 5500U'
 'Radeon R4 Dual-Core' 'Intel Core i3/i5' 'INTEL Core i7-7Y75'
 'Intel Pentium N4200' 'Intel Pentium N Quad Core' 'MediaTek'
 'Intel Celeron N4000' 'Intel Core i7-5600U' 'Apple M1 chip'
 'Intel Core i5-7300U' 'INTEL CORE i5' 'Intel Pentium III' 'i5-8350'
 'Intel Celeron D' 'not specified' 'AMD Turion II' 'Mediatek M8173c'
 'Intel Celeron 4100' 'Intel Pentium Gold 8505' 'AMD Athlon Gold 3150U'
 'See Title/Description' '12th Gen Intel® Core™ i5-12450H Processor'
 'Celeron R' '1660Ti' 'Qualcomm Kryo 468' 'Intel Core i7-6600U'
 'AMD Ryzen 3 Pro' 'Intel Celeron N2940 1.83GHz Quad'
 'Intel Core I5-8300H' 'Intel Core i5-6200U' 'MediaTek 820 (8192)'
 'Intel Core i3-1215U' 'i7-1165G7' 'Core i5-10210U' 'Intel Corei7-8850H'
 'intel core i5 8th gen' 'AMD Ryzen 7 PRO 4750U' 'NVIDIA Tegra K1'
 'Intel core i7 4th gen'
 'Intel Core i7 3rd gen,  4 cores,  8 logical processors'
 'Intel Core i5 5300U' 'Dual Core' 'Intel i5 6th Gen.' 'AMD Ryzen 9'
 'Intel Core' 'Intel Core i5 6300U' 'intel i5' 'AMD A6-7310 APU'
 'Intel Core i7 5th Gen.' 'Intel i7 2nd Gen.' 'AMD A8-7410 4-Core 2.50GHz'
 'Quad-Core Intel N100' 'Intel Inside' 'Rockchip RK 3288'
 'Intel Core i5 4th Gen. 2.70GHz' 'i7-6600U' 'Intel Core I-5'
 'Intel Core i3 5th Gen.' 'AMD E-Series' 'AMD A6-9220C' 'AMD Radeon R4'
 'Intel Core i5 1st gen.' 'intel core i7' 'core i5' 'AMD A4-5000'
 'Pentium D' 'Intel Core I7-7700HQ CPU' 'AMD A9' 'Intel Core i5-L16G7'
 'Intel i3-5020u' 'Intel Core i7 3.40 GHz (Max Turbo Speed: 3.80 GHz)'
 'Not Applicable' 'i5 L16G7' 'Intel Core i5 8th Gen' 'Intel Core i5-2520M'
 'AMD Ryzen 5-3550H' '6300U, Core i5' 'AMD Ryzen 5 3rd Gen.' 'Apple M1'
 'INTEL CELERON N2840' 'Intel Celeron N3050 1.6GHz Dual-Core'
 '13th Gen Intel® Core™ i5-13420H Processor'
 'Arm Rockchip Rk3288 Cortex A17 Quad-CORE' 'Backpack'
 'Intel Core i7 i7-1355U' 'AMD A6 Quad-Core' 'Intel Celeron N3060'
 'intel core i3' 'AMD Ryzen 7 PRO 6850U' 'intel core i5 6th gen'
 'AMD Ryzen 7 Quad-Core' 'Intel i5-2520m' 'Intel Core i5-1235U'
 'AMD A8 Quad-Core' 'see photos' 'Intel Core i7-4700 @ 2.4 GHz'
 'Core i7 8th gen.' 'i7-6500U' 'Intel Celeron M' 'intel Atom x5 z8350'
 'Intel Centrino' 'Intel Core  i5-8350U' 'Intel Core i5 7th Gen'
 'Intel Core i7 Extreme 4th Gen.' 'Pentium M' 'Intel Core i7-8650U'
 'i7-3630qm@2.4ghz' 'AMD A10' 'Intel Pentium Silver' '6300U'
 'Intel Core 2 Duo, Intel Core 2 Duo T7100 (1.8GHz)'
 'Qualcomm® Snapdragon™ 8cx Gen 2' 'Intel Core i5 Mobile'
 'Intel Core i7 9850H' 'Intel A100' 'DOES NOT APPLY' 'Intel Core i3-1220P'
 'AMD Turion 64' 'Intel Core i5-10310U' 'Intel Core i7 7th generation'
 'I5-10210U' 'A10-8730B' 'Intel Pentium N-Series'
 'Intel® Core™ i5 i5-5200U' 'Qualcomm Snapdragon 7c'
 'Intel Core Duo T2300' '6300U,  Core i5' 'AMD Ryzen 7 5825U'
 'Intel Core i7-6820HQ' '13th Gen Intel® Core™ i9-13900H Processor'
 'AMD INTEL' 'Core i3' 'Intel Celeron N2920' 'Ryzen 5 5625U' 'Intel Atom'
 'intel core i7 6th gen' 'Amd 7th generation'
 'Intel i5-7200U @2.50 GHz,  2701 Mhz,  2Core(s)' 'AMD Ryzen Pro 3'
 'AMD Turion X2' 'Intel Core i5-3210M' 'INTEL I5 10TH GEN' 'core i5 m520'
 'UNKNOWN' 'Intel fast processor' 'Core i7 4th Gen' 'i7-4600M'
 'Core i5 8250U' 'Microsoft SQ1' 'i7-7660U' 'Amd A6'
 'Intel Xeon E-2176M CPU' 'AMD Athlon XP' 'Intel Core i5-5200U' 'I5-7y54'
 'Intel Pentium N5030' 'i7' 'Intel Celeron N4120' 'Intel Core i5-1035G1'
 'Intel Core Duo' 'Intel DUAL Core Quad Thread Pentium 4415U 2.30GHz'
 'Intel Core M3' 'AMD Ryzen 5 6000 Series' 'Intel Celeron N4500 Processor'
 'Intel Core i7-1260U' 'Intel or AMD' 'AMD Ryzen 5 4500U'
 'Intel® Core™ i3 i3-3217U' 'Core I3-4030u' 'Intel Core I7'
 'INTEL CORE I5' 'i7-4800' 'Intel Core i9 12th Gen'
 '11th Generation Intel® Core™ i7-1165G7' 'Intel Core i7-6500U'
 'Quartz or automatic' 'Intel Celeron Dual Core' 'Pentium'
 'Intel Core i7 10th generation' 'N3530' 'AMD Ryzen 5 3550H'
 'Core i7 6th gen.' 'Qualcomm Snapdragon 8cx Gen 3 SC8280XP' 'i7-6820HQ'
 'i5-5300U' 'Intel Core i5 8th Gen. 8250U' 'Intel Core 2 Duo T6600'
 'I5-8259u' 'MediaTek Helio P60T' '8650U' 'Core i5-8350u 8th' 'AMD 3015Ce'
 'Intel Core 13th Generation i5-1345U Processor (10 Core, Up to 4.7'
 'Core i5-3437U' 'Intel Core i5-4300M CPU @ 1.90 GHz'
 'Intel Core i7-1165G7' 'Intel Celeron n4020' 'Intel Core i3 1st Gen.'
 'Intel i7 Quad-Core' 'Intel i7 8th Gen' 'i7-8565u' 'NONE' 'M7-6Y75'
 'Intel Core i7-10610U' 'Intel Core i7-7500U'
 'Intel Core i7-12700H Processor 2.3 GHz' 'i5-6' 'Intel Pentium 4'
 'intel Core i5-5300U' 'i5-1135G7' 'Intel Core i7-10610U (10th Gen CPU)'
 'Mixt' 'AMD Ryzen 5 5625U' 'A72/A53 2.0GHz' 'i7-8650U'
 'Intel Core m3 8th Gen.' 'Intel(R) Atom (TM) x7-Z8750 CPU @ 1.60GHz'
 'AMD A4-9120e' 'i7-10610U' 'Intel Core i5-6300U 2.40GHz'
 'Rockchip RK3288-C' 'AMD A6-9220E'
 'Intel Core i7-7Y75 (up to 3.60GHz, 4M Cache)' 'Intel Core i5 6th gen'
 'i7-13800H' 'na' 'Core i5' 'Core  i3-6100U' 'Intel Core i7-9750H' 'i3'
 'Intel Core i7-11800H' 'Ryzen' 'none' 'Intel® Atom™'
 'Intel Core i5-10400H' 'Cable' 'AMD Ryzen 7 5800HS' 'Intel Core I7 8650u'
 'Core i7 6600U 2.60GHz' 'intel mobile']

In [21]:
# I wrote if-elif statements to standardize processor names, and I used ChatGPT to help me troubleshoot and make it clean
# Citation: ChatGPT. (2025, September 9). Conversation with ChatGPT about cleaning and classifying processor values in Python/pandas. OpenAI. Personal communication.

def map_processor(processor):
    if pd.isna(processor):
        return "Unknown"
    p = str(processor).lower()

    if "a9 chip" in p or "m1" in p:
        return "Apple"
    elif "ryzen" in p:
        return "AMD Ryzen"
    elif "amd" in p:
        return "AMD Legacy"
    elif any(x in p for x in ["i3", "i5", "i7", "i9"]):
        return "Intel Core"
    elif "core" in p or "intel" in p:
        return "Intel Other"
    elif any(x in p for x in ["qualcomm", "tek", "samsung", "google", "nvidia", "rockchip", "microsoft", "arm"]):
        return "ARM/Mobile"
    else:
        return "Unknown"

pc_df["Processor"] = pc_df["Processor"].apply(map_processor)

In [23]:
# Check work
processor_unique_values = pc_df['Processor'].unique()
print(f"There are {len(processor_unique_values)} unique Processor values: {processor_unique_values}")

There are 7 unique Processor values: ['Intel Other' 'Intel Core' 'AMD Ryzen' 'Unknown' 'AMD Legacy'
 'ARM/Mobile' 'Apple']

In [23]:
# Verify no missingness in Processor column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size            39.71
Color                  66.49
Ram Size               66.49
SSD Capacity           56.45
GPU                    53.01
Processor Speed        58.37
Type                   49.08
Release Year           87.32
Maximum Resolution     61.40
Model                  50.95
OS                     52.70
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note            76.99
Price                   0.00
dtype: float64

### Screen Size Column

In [24]:
# get list of unique values for Screen Size column
screen_unique_values = pc_df['Screen Size'].unique()
print(f"There are {len(screen_unique_values)} unique Screen Size values: {screen_unique_values}")

There are 159 unique Screen Size values: ['14 in' '11.6 in' 'Minimum 12.5"' '11.6 inin' '13.3 in' '14.1 in' '2 in'
 '15.6 in' '11 in' '16 in' '12.5 in' nan '13 in' '12 in' '15.6" 1080P FHD'
 '13.5 in' '17.3 in' '18.4 in' '12.3 in' '10.1 in' '14.1in.' '14"'
 '7.2 in' 'Does not apply' '15,6"' '12, 5"' '13, 3"' '15.4 in' '13,3"'
 '14,1 Zoll (35,8 cm)' '12,5"' '14" 35, 5cm' '15, 6"' '14, 1"'
 '15.6 inches' '13"' '15"' '17 in' '15 in' '9.7 In' '8.1 in' '11.6"'
 '10.95 in' '14.1"' '7 in' '17.3in' '11, 6"' '14,1"' '10, 8"' '?' '10,8"'
 '15, 4"' '11,6"' '18 in' '14' '15.6&quot;' '16.1 in' '14 inin'
 '14" Touchscreen' '13, 5"' '14" touchscreen' 'WIDE' '10.5 in' '12.5'
 'Various' '15,4"' '15.6"' '10.8 in' '12.1 in' '12.2 in' '16.0 in'
 '12.5in' '14" HD Matte Display' '14 inch' '13.4 in' '15&quot;'
 '12 in In.3in.' '14.0"' '13.3"' '10.4 in' '17.3' '12.5" or above'
 '12" LED Touchscreen (Outdoor Viewable)' '13" 14\'' '10 in'
 'GLASSES SCREEN' '14 In' 'See Title' '15.6' '14 in.' '15.6" Touch Screen'
 '15.5 in' '13in' '15.6 In' '14.5 in' '12.5" FHD (1920x1080)' '12.5"'
 '11.5 in' "15.6'" '11.6 in in in in in in in in in Inin.'
 'Not Applicable' '13.3in' '15.6in.' '14 Inch' '10.3 in'
 '12.5"/13.3"/14.1"' '10.1in' '10.2 in' '14&quot;' '14in.' '13.7 in'
 '15 in In.4in.' '11.6 inin.' 'DOES NOT APPLY' '17.3"' '13.2' '13.9 in'
 '10.8 "' '13.3in.' '9.5 in' '12.3"' '6.1 in' '16 inch' '13.1 in' '13.3'
 '15.6 In.' 'Does Not Apply' '12.5-15.6' '15.5"' 'Jumbo Heuer 1000'
 '14.2 in' '12.4 in' '13,5"' '12,1' '8.1' '15.6in' 'Laptop, in'
 '10.1" LED Touchscreen (Outdoor Viewable)' '4.5 in' '15.6 in FHD'
 '12.5" Full HD Touch' '11.6 in in Inin.' 'Mixt' '9.7 in' '10.5' '15.4"'
 '17,3"' '12.5in.' '13.3" QHD+ 3K Touch Screen' 'na' '15.6 inin' '13.3 In'
 '14 in - 15.6"' 'none' '13.3" touchscreen' '14in' '2 Meter' '12  Zoll'
 '14 in or Bigger']

In [25]:
# Create categories of screen size
# Make clear in analysis and information relay that I chose to classify
#   any screen size in between integer values as the minimum in the range [x to x+1)
#   for example, 14.2 inch would be classified as "14" category which encompasses [14 to 15) inch screens

def map_screen_size(screen_size):
    if pd.isna(screen_size):
        return "Unknown"
    ss = str(screen_size).lower()

    if "various" in ss or "or bigger" in ss or "minimum" in ss:
        return "Various"
    elif "16" in ss:
        return "16"
    elif "15" in ss:
        return "15"
    elif "14" in ss:
        return "14"
    elif "13" in ss:
        return "13"
    elif "12" in ss:
        return "12"
    elif "11" in ss:
        return "11"
    elif "10" in ss:
        return "10"
    elif "9" in ss:
        return "9"
    elif "8" in ss:
        return "8"
    elif "7" in ss:
        return "7"
    else:
        return "Unknown"

pc_df["Screen Size"] = pc_df["Screen Size"].apply(map_screen_size)

In [26]:
# Check work
screen_size_unique_values = pc_df['Screen Size'].unique()
screen_size_unique_values.sort()
print(f"There are {len(screen_size_unique_values)} unique Screen Size values: {screen_size_unique_values}")

There are 12 unique Screen Size values: ['10' '11' '12' '13' '14' '15' '16' '7' '8' '9' 'Unknown' 'Various']

In [27]:
# Verify no missingness in Screen Size column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                  66.49
Ram Size               66.49
SSD Capacity           56.45
GPU                    53.01
Processor Speed        58.37
Type                   49.08
Release Year           87.32
Maximum Resolution     61.40
Model                  50.95
OS                     52.70
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note            76.99
Price                   0.00
dtype: float64

### Color Column

In [28]:
# get list of unique values for Color column
color_unique_values = pc_df['Color'].unique()
print(f"There are {len(color_unique_values)} unique Color values: {color_unique_values}")

There are 83 unique Color values: ['Gray' 'Black' nan 'Gray, Granite Gray' 'Silver' 'Natural Silver'
 'Dark Brown' 'Carbon Black' 'Grey/Black' 'Multi' 'Arctic Grey' 'Blue'
 'Multicolor' 'Black/Gray' 'Negro' 'Gris' 'Mica Silver' 'Steam Blue'
 'Purple' 'Platino' 'borgoña' 'Dark Metallic Moon'
 'Black/ Blue / Sandtone / Platinum' 'Dark Grey' 'Silver, Metallic Silver'
 'Pink' 'Black / Grey' 'Grey' 'Beige' 'Red' 'White' 'Gray and Black'
 'Silver/Black' 'Standard' 'Abyss Blue' 'Silver, Platinum Silver' 'Green'
 'Brown' 'Cloud Grey' 'Warm Gold' 'Black/Blue' 'Storm Gray' 'See Photos'
 'Mineral Grey' 'Yellow' 'Orange' 'see pictures' 'Silver + Black'
 'Pure Silver' 'Platinum' 'Black / Silver' 'BLK' 'Immaculate' 'Blanco'
 'black' 'Charcoal Gray' 'Plata Transparente' 'BLACK' 'Sandstone'
 'Fog Blue Aluminum' 'Matte Black' 'Bronze' 'Silver / Black'
 'Gray, Platinum Silver' 'Silver & Black' 'Gray / Silver' 'STEEL GRAY'
 'Gray, Blue' 'Multi-Color' 'Gold' 'Jet Black' 'Teal' 'Platinum Silver'
 'Eclipse Gray' 'Gun Metal' 'Mineral Silver' 'Black/Red' 'Space Gray'
 'Tech Black' 'Silver and Black' 'Black / Gray' 'Silver, Black'
 'Quiet Blue']

In [30]:
# Create categories of color tones
# Ask ChatGPT to group these values into three tone categories: grayscale, earth tones, bright tones
# Citation: ChatGPT. (2025, September 9). Conversation with ChatGPT about cleaning and classifying laptop colors in Python/pandas. OpenAI. Personal communication.

def map_color(color):
    if pd.isna(color):
        return "Unknown"
    c = str(color).lower()

    # Grayscale / neutral tones
    if any(x in c for x in ["gray", "grey", "black", "white", "silver", "platinum", "metal", "charcoal"]):
        return "Grayscale"

    # Bright tones
    elif any(x in c for x in ["blue", "red", "purple", "pink", "yellow", "orange", "teal", "multi"]):
        return "Bright"

    # Earth tones
    elif any(x in c for x in ["brown", "beige", "sand", "bronze", "gold"]):
        return "Earth"

    else:
        return "Unknown"

pc_df["Color"] = pc_df["Color"].apply(map_color)

In [31]:
# Check work
color_unique_values = pc_df['Color'].unique()
print(f"There are {len(color_unique_values)} unique Color values: {color_unique_values}")

There are 2 unique Color values: ['Grayscale' 'Unknown']

In [31]:
# Verify no missingness in Color column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                   0.00
Ram Size               66.49
SSD Capacity           56.45
GPU                    53.01
Processor Speed        58.37
Type                   49.08
Release Year           87.32
Maximum Resolution     61.40
Model                  50.95
OS                     52.70
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note            76.99
Price                   0.00
dtype: float64

### Ram Size Column

In [32]:
# get list of unique values for Ram column
ram_unique_values = pc_df['Ram Size'].unique()
print(f"There are {len(ram_unique_values)} unique Ram Size values: {ram_unique_values}")

There are 59 unique Ram Size values: ['8 GB' nan '16 GB' '4 GB' '2GB' '32 GB' '4 MB' 'Up to 32GB' '12 GB'
 '256 GB' '1 GB' '20 GB' '3 GB' '16GB' '4GB' '8GB' 'Up to 64GB' '24 GB'
 '16GB DDR4 RAM' '16gb' '2 GB' '6 GB' '64 GB' '8 GB DDR4'
 '8GB / 16 GB OR 32GB SELECT FROM ABOVE' '8 GB RAM'
 '8GB,  16GB,  32GB,  64GB' '8192MB' 'Unknown' '512 GB' '20gb'
 'Up to 36 GB' 'Not Included' '16 GB RAM' '8gig' 'up to 32GBGB DDR4' '4gb'
 '64 MB' '8' '12GB' '8GB DDR4' '8gb'
 '8 GB DDR4 Installed---Can upgrade o 32GB DDR4' '32GB' '20GB'
 '8 GB 16 GB 32 GB' '1GB' '128 GB' '12gb' '1Gb' '40 GB' 'Up to 40GB'
 'Up to 32 GB' '4 GB DDR4' '4GB - 16 GB' '24GB' '512 MB' '16 GB DDR4'
 '4 GB- 8 GB']

In [34]:
# Standardize RAM Size with help from ChatGPT
# Citation: ChatGPT. (2025, September 9). Conversation with ChatGPT about cleaning and standardizing RAM size values in Python/pandas. OpenAI. Personal communication.

import re

def map_ram(ram):
    # Address missing and unknown values
    if pd.isna(ram):
        return "Unknown"
    r = str(ram).lower().strip()

    if any(x in r for x in ["unknown", "not included"]):
        return 'Unknown'
    
    # If RAM value has a number, create a RAM size local variable and extract the digits only;
    #    otherwise, label it as 'unknown' because we cannot make conjecture about an unknown value here.
    match = re.search(r"(\d+)", r)
    if not match:
        return "Unknown"
    size = int(match.group(1))

    # Standardize to only GB values: convert from MB to GB: 1024 MB = 1 GB
    if "mb" in r:
        size = round(size / 1024)
        # Handle zero values: We cannot know how much RAM if the value is 0, so we label as 'Unknown'
        if size == 0:
            return "Unknown"

    # Standardize the RAM values and return as a properly formatted GB string value
    if "64" in r:
        size = 64
    elif "40" in r:
        size = 40
    elif "36" in r:
        size = 36
    elif "32" in r:
        size = 32
    elif "24" in r:
        size = 24
    elif "20" in r:
        size = 20
    elif "16" in r:
        size = 16
    elif "12" in r:
        size = 12
    elif "8" in r:
        size = 8
    elif "6" in r:
        size = 6
    elif "4" in r:
        size = 4
    elif "3" in r:
        size = 3
    elif "2" in r:
        size = 2
    elif "1" in r:
        size = 1
    elif "128" in r:
        size = 128
    elif "256" in r:
        size = 256
    elif "512" in r:
        size = 512

    return f"{size} GB"

# Map the result to the DataFrame
pc_df["Ram Size"] = pc_df["Ram Size"].apply(map_ram)

In [35]:
# Check work
ram_unique_values = pc_df['Ram Size'].unique()
print(f"There are {len(ram_unique_values)} unique Ram Size values: {ram_unique_values}")

There are 15 unique Ram Size values: ['8 GB' 'Unknown' '16 GB' '4 GB' '2 GB' '32 GB' '12 GB' '6 GB' '1 GB'
 '20 GB' '3 GB' '64 GB' '24 GB' '36 GB' '40 GB']

In [ ]:
# Verify no missingness in RAM column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

### SSD Column

In [37]:
# get list of unique values for Ram column
ssd_unique_values = pc_df['SSD Capacity'].unique()
print(f"There are {len(ssd_unique_values)} unique SSD values: {ssd_unique_values}")

There are 74 unique SSD values: ['1 Used,  1 support Max 1TB M.2 Extend' nan '500 GB' '256 GB' '16 GB'
 '16GB' '64 GB' '128 GB' '32 GB' '512 GB' '1 TB' 'Up to 2TB' '120 GB'
 'Not Included' 'See Options' '240GB' '32GB' '480GB' '256GB' '120GB'
 '240 GB' '960GB' '2TB' '4TB' '128GB' '1tb' '360GB' 'na' '0gb' 'NONE'
 'M.2 120GB + HDD 1TB' '500GB' '0' '250 GB'
 'FROM 120GB TILL 1TB SSD SELECT FROM ABOVE' '64gb' '2 TB' 'Not Include'
 '128GB,  256GB,  500GB,  1TB,  2TB' '4 tb' 'Not Applicable' 'Up to 1 TB'
 '1 TB(not in)' '512GB' 'No SSD' '1TB + 1TB' '4 GB'
 '256 GB / 512GB / 1TB SSD' 'up to 1TB SSD' '500 GB HDD' '931.51GB'
 '500gb' '256 GBSSD' '16 GB SSD' '1TB Hard Drive (Not SSD)' '512gb'
 '800gb' '.' '512' '256gb' '180GB' '476GB' 'Up to 2 TB' '120GB - 1TB'
 '160 GB' '256SSD' 'NO' '1024 GB' '512 GB SSD' '115gb' '120'
 '64GB Solid State Drive' '120 GB - 240 GB' '120 GB - 500 GB']

In [41]:
# Standardize SSD Capacity with help from ChatGPT
# Citation: ChatGPT. (2025, September 9). Conversation with ChatGPT about cleaning and standardizing SSD capacity values in Python/pandas. OpenAI. Personal communication.

def map_ssd(ssd):
    if pd.isna(ssd):
        return "Unknown"
    s = str(ssd).lower().strip()

    # Address missing / unknown values
    if any(x in s for x in ["not included", "not include", "not applicable", 
                            "no ssd", "none", "na", "see options", ".", "0gb", "0"]):
        return "Unknown"

    # Extract all groups of digits from entries, 
    # and replace those without numbers as unknown amount of storage
    numbers = re.findall(r"\d+\.?\d*", s)
    if not numbers:
        return "Unknown"

    sizes = []
    for n in numbers:
        val = float(n)

        # Find and format all TB values
        if "tb" in s:
            val = int(round(val))
            
            # Check for typos; more than 100 TB is non-standard and unlikely for a laptop
            if val > 100:
                return f"{val} GB"
                
            sizes.append(f"{val} TB")

        # Find and format all GB values
        elif "gb" in s:
            val = int(round(val))

            # Normalize known unique values
            # I chose this to maintain the fullness of the dataset. Logically, 
            #    some SSD values might be slightly lower than standard values because
            #    the Ebay user wanted to highlight the amount of USABLE space when
            #    accounting for pre-installed partition of the storage space
            if val == 115:
                val = 120
            if val == 476:
                val = 512

            sizes.append(f"{val} GB")

        else:
            # If no unit label is given, make a logical connection to the number and standard SSD values
            # Since it is highly unlikely that a laptop has 1000 TB SSD, we can safely say that
            #    these are probably GB values and convert the value to corresponding TB values
            if val >= 1000:
                if abs(val - 1024) <= 50: return "1 TB"
                if abs(val - 2048) <= 100: return "2 TB"
                if abs(val - 4096) <= 200: return "4 TB"
                sizes.append(f"{int(val)} GB")
            else:
                # Catch and standardize known unique values
                if int(val) == 115:
                    val = 120
                if int(val) == 476:
                    val = 512
                sizes.append(f"{int(val)} GB")

    # Catch any other values not GB or TB
    if not sizes:
        return "Unknown"

    # Normalize GB-to-TB conversions
    def normalize(v):
        if v.endswith("GB"):
            num = int(v.replace(" GB", ""))
            if num == 1024: return "1 TB"
            if num == 2048: return "2 TB"
            if num == 4096: return "4 TB"
            return f"{num} GB"
        return v

    # If there is a range of values, keep the maximum value
    max_size = max(sizes, key=lambda x: int(re.findall(r"\d+", x)[0]))
    return normalize(max_size)

pc_df["SSD Capacity"] = pc_df["SSD Capacity"].apply(map_ssd)

In [42]:
# Check work
ssd_unique_values = pc_df['SSD Capacity'].unique()
ssd_unique_values.sort()
print(f"There are {len(ssd_unique_values)} unique SSD Capacity values: {ssd_unique_values}")

There are 11 unique SSD Capacity values: ['1 TB' '128 GB' '16 GB' '2 TB' '256 GB' '32 GB' '4 GB' '4 TB' '512 GB'
 '64 GB' 'Unknown']

In [43]:
# Verify no missingness in SSD column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                   0.00
Ram Size                0.00
SSD Capacity            0.00
GPU                    53.01
Processor Speed        58.37
Type                   49.08
Release Year           87.32
Maximum Resolution     61.40
Model                  50.95
OS                     52.70
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note            76.99
Price                   0.00
dtype: float64

### Seller Note Column

In [44]:
# Since seller notes are all different, there may be some business interest in analyzing in regards 
#    to whether there exists a note or not, and if that increases price or selling point.
# Therefore, I chose to assign 0 to any missing values, and 1 to any full values

def map_note(note):
    if pd.isna(note):
        return 0
    else:
        return 1

pc_df["Seller Note"] = pc_df["Seller Note"].apply(map_note)

In [45]:
# Check work
note_unique_values = pc_df['Seller Note'].unique()
print(f"There are {len(note_unique_values)} unique Seller Note Capacity values: {note_unique_values}")

There are 2 unique Seller Note Capacity values: [0 1]

In [46]:
# Verify no missingness in Seller Note column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                   0.00
Ram Size                0.00
SSD Capacity            0.00
GPU                    53.01
Processor Speed        58.37
Type                   49.08
Release Year           87.32
Maximum Resolution     61.40
Model                  50.95
OS                     52.70
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note             0.00
Price                   0.00
dtype: float64

### GPU Column

In [47]:
# get list of unique values for GPU column
gpu_unique_values = pc_df['GPU'].unique()
print(f"There are {len(gpu_unique_values)} unique GPU values: {gpu_unique_values}")

There are 271 unique GPU values: ['Intel Iris Plus Graphics 655' 'Intel UHD Graphics 620'
 'Intel HD Graphics' 'Intel HD Graphics 500' 'Integrated' nan
 'Intel UHD Graphics' 'Intel UHD Graphics 600'
 'Intel UHD Graphics 600, 650MHz' 'Intel HD Graphics 620'
 'AMD Radeon Graphics' 'Intel UHD 620 1024 MB' 'Intel Iris Xe Graphics'
 'NVIDIA GeForce RTX 3050 Ti' 'Intel HD Graphics 4400'
 'Intel® UHD Graphics' 'Intel® HD Graphics 520'
 'NVIDIA GeForce GTX 1050 Ti' 'Mali-G72 MP3' 'NVIDIA GeForce RTX 3050'
 'Intel HD Graphics 630' 'Intel HD Graphics 520' 'Intel HD Graphics 4000'
 'Intel HD Graphics 400' 'Intel 965 GM (CL)' 'Intel HD Graphics 5300'
 'INTEL HD-GRAFIK 620' 'Gráficos Intel HD 5500' 'Intel UHD Graphics 605'
 'Intel GMA 950' 'Nvidia GeForce GT720M' 'Carte graphique Intel HD 5500'
 'Carte graphique Intel HD 4400' 'Carte graphique Intel UHD 620'
 'Carte graphique Intel HD 520' 'Carte graphique Intel HD 620'
 'intel GMA 950' 'Intel HD Graphics 4600' 'Gráficos Intel HD 4200'
 'intel HD Graphics 4400' 'Gráficos Intel UHD 620'
 'Carte graphique Intel HD 4000' 'Carte graphique Intel HD 5300'
 'INTEL HD GRAPHICS 520' 'GRAPHIQUE INTEL HD 620' 'Intel HD Graphics 4200'
 'GRAPHIQUE INTEL HD 520' 'Intel HD Graphics 5500'
 'Gráficos Intel HD 4400' 'GrÃ¡ficos Intel HD 620' 'INTEL HD GRAPHICS 620'
 'AMD Radeon Grafica' 'Intel HD Graphics 510' 'Gráficos Intel HD 3000'
 'Gráficos Intel HD 4000' 'Gráficos Intel HD 520'
 'NVIDIA GeForce GTX 1650' 'Carte graphique Intel HD 4200'
 'GRÁFICOS INTEL HD 620' 'Carte graphique Intel HD 500'
 'Intel Blu Iris C20 Xe Gráficos' 'Intel UHD-Grafik 620'
 'Intel HD Graphics 3000' 'Gráficos Intel HD 4600' 'NVIDIA Quadro M1000M'
 'NVIDIA Quadro M2000M' 'Intel(R) HD Graphics 620' 'NVIDIA Quadro 1000M'
 'NVIDIA GEFORCE GT 730M' 'intel HD Graphics 5500'
 'Carte graphique Intel HD 4600' 'Scheda grafica Intel HD 505'
 'AMD Radeon HD 8670M' 'Carte graphique Intel HD 510'
 'Intel Blu Iris C20 Plus Gráficos' 'Gráficos Intel Iris Plus 640' 'M1200'
 'NVIDIA GeForce RTX 4080' 'intel' 'Nvidia Quadro P3200'
 'NVIDIA GeForce RTX 4060' 'Intel Iris Graphics 550'
 'Intel HD Graphic 4400' 'Intel Iris Plus Graphics'
 'AMD Radeon HD8790M 2GB GDDR5' 'Gráficos Intel HD 620'
 'AMD Radeon Gráficas' 'Graphiques Intel Iris Xe'
 'Intel Iris Plus-Grafik 640' 'Intel HD-Grafik 4400' 'INTEL HD-GRAFIK 520'
 'enthalten' 'Carte graphique Intel HD 3000'
 'Intel Iris Pro Graphics 5200' 'Intel' 'Intel HD Gráficos 520'
 'Intel HD Graphics 5000' 'Intel Graphics' 'P5000' 'HD Graphics 520'
 'Intel UHD Gráficos' 'intégré' 'NVIDIA GEFORCE RTX 3050'
 'AMD Radeon HD 6250' 'NVIDIA GEFORCE RTX 3050 LAPTOP' 'Intel HD'
 'AMD Radeon R4' 'NVIDIA Quadro RTX 3000' 'GeForce GT 630' 'Intel GMA'
 'NVS 4200M w/ 1GB' 'Qualcomm Adreno 690' 'AMD Radeon HD 7650M'
 'NVIDIA GeForce RTX 3050Ti' 'Celeron' 'AMD Radeon RX Vega 10'
 'NVIDIA Quadro RTX 4000' 'Intel HD Graphics 615'
 'Integrated Intel HD Graphics'
 'Nvidia Quadro M1200 4GB (i7-7th Gen),  M1000M 2GB (i7-6th Gen)'
 'NVIDIA GeForce GT 730M' 'Radeon Vega Mobile Gfx' 'NVIDIA Quadro K1000M'
 'NVIDIA Quadro M2200' 'NVIDIA Quadro P1000' 'NVidia Quadro 2000M'
 'NVIDIA Quadro T1000' 'NVIDIA Quadro P520' 'Intel UHD Graphics 520'
 'NVIDIA Quadro P3200 with 6GB GDDR5 dedicated memory'
 'Qualcomm Adreno 618' '2GB Nvidia Quadro M1000M'
 'Intel HD Graphics 4600 + AMD Radeon HD 8790M' 'NVIDIA RTX A2000'
 'Intel HD Graphics 530' 'Intel® UHD Graphics 600, 250-750MHz'
 'Intel UHD Graphics 615' 'NVIDIA GeForce RTX 2050' '\u200ePowerVR GX6250'
 'GTX 1650' 'Intel UHD Graphics G1' 'ATI Mobility Radeon X600'
 'Intel UHD Graphics for 8th Generation Processors' 'Nvidia Quadro P1000'
 'YOGA' 'AMD FirePro M5800 w/ 1GB DDR3' 'Iris Xe Graphics'
 'Intel UHD Graphic' 'NVIDIA Quadro P5000' 'AMD Radeon 7 Graphics'
 'NVIDIA GeForce RTX 4090' 'INTEL UHD 620' 'Intel HD Graphics 505'
 'NVIDIA GeForce RTX 2070' 'NVIDIA GeForce RTX 3070 Ti'
 'AMD Radeon Vega 8' 'NVIDIA RTX A1000,  6 GB GDDR6' 'INTEL HD'
 'NVIDIA GeForce GTX 1050' 'NVIDIA GeForce 9400M'
 'NVIDIA GeForce GTX 860M' 'NVIDIA GeForce GTX 1660 Ti'
 'Intel(R) UHD Graphics 620' 'Intel HD 400'
 'Integrated Intel UHD Graphics 630' 'NVIDIA Quadro T2000' 'UHD Graphics'
 'NVIDIA NVS 5400M' 'Intel HD 520 Graphics' 'AMD Radeon 780M'
 'NVIDIA GeForce MX550' 'AMD R4 Graphics'
 'Intel(R) HD Graphics P630,  NVIDIA Quadro M620' 'AMD Radeon PRO WX 2100'
 'AMD Radeon R5 Graphics' 'Intel Core i5 11th Gen.' 'AMD Radeon R7 M350'
 'INTEL HD GRAPHICS 5500'
 'Intel UHD Graphics for 10th Generation Processors'
 'Intel UHD Graphics 630' 'Integrated/On-Board Graphics'
 'NVIDIA GeForce RTX 2060' 'AMD Radeon HD 7310'
 'AMD Radeon RX 560X - 4GB / AMD Radeon Vega 8 Graphics'
 'NVIDIA GeForce RTX 3060' 'Integrated Intel UHD Graphics'
 'AMD Radeon Pro WX 3200' 'Core™ i7' 'Gaming' 'M1 8-Core'
 'AMD Radeon R4 Graphics' 'Core™ i5' '.' 'NVIDIA GeForce RTX 3070'
 'nvidia 850m' 'AMD FirePro W4190M' 'Intel(R) HD Graphics 520'
 'NVIDIA GeForce MX150' 'Intel HD Graphics 515' 'NVIDIA GeForce GT 750M'
 'ATI Radeon Mobility X300' 'NVIDIA GeForce GTX 1050 2 GB'
 'AMD Radeon Vega 7' 'ATI Radeon Xpress Series'
 'Intel Integrated Graphics' 'Microsoft SQ2 Adreno'
 'Intel HD Graphics 6000' 'Intel® Iris XE' 'Nvidia GeForce RTX 2050'
 'HD Graphics 5500' 'NIDIA NVS 5200M' 'Intel Iris Plus'
 'Intel Iris Xᵉ Graphics' 'P3000' 'Intel Graphics Family'
 'Nvidia Geforce RTX 1650' 'NVIDIA Quadro M620' 'ARM Mali-G72'
 'Quadro M620' 'NVIDIA GeForce RTX 2080' 'Microsoft SQ1 Adreno 685'
 'HD 520' 'AMD Radeon Vega 6' 'NVIDIA Quadro P2000 With Max-Q Design'
 'Nvida Quadro K1000m' 'Onboard' 'Intel HD 520'
 'Intel(R) Iris(R) Xe Graphics' 'NVIDIA GeForce RTX 3080' 'HD Graphics'
 'Intel® HD Graphics' 'NVIDIA GeForce MX350' 'Intel HD 4000'
 'Intel HD Graphics 610' 'AMD Radeon R7 M365X' 'Intel Celeron N4020'
 'Intel® Iris® Xe Graphics' 'GrÃ¡ficos Intel HD 4600'
 'Intel Iris Plus Graphics 640' 'AMD R5 M330'
 'NVIDIA GeForce RTX 2080 Super' 'Carte graphique Intel Iris Plus 640'
 'Intel GMA X4500HD' 'Integrated Graphics'
 'Integrated Qualcomm Adreno 690 Graphics' 'Intel Core i3-1005G1'
 'AMD Radeon™ Graphics' 'NVIDIA GeForce GPU' 'NVIDIA GeForce MX450'
 'NVIDIA Quadro K1100M 2GB' 'NVIDIA GeForce MX250' 'Intel Integrated'
 'NVIDIA Geforce 4200m' 'Nvidia GeForce FX5200'
 'AMD Radeon R7 M260 2GB DDR3' 'Mobile Intel Express Chipset Family'
 'Intel Arc 370M' 'Qualcomm Adreno 685' 'AMD Radeon RX540'
 'AMD Radeon 4GB GPU' 'NVIDIA GeForce 320M' 'Nvidia Quadro P2000'
 'Nvidia Geforce GTX 1650 with MAX-Q Design 4096MB'
 'NVIDIA GeForce GTX 1650 Ti' 'Intel HD Gráficos'
 'Intel® UHD Graphics 600' 'GrÃ¡ficos Intel HD 4000'
 'CometLake-U GT2 [UHD Graphics]' 'WhiskeyLake-U GT2 [UHD Graphics 620]'
 'Intel HD-Grafik 4000' 'Gráficos Intel Iris 520']

In [48]:
def map_gpu(gpu):
    if pd.isna(gpu):
        return "Unknown"
    p = str(gpu).lower()

    # Group GPUs into four standard, recognizable categories
    if any(x in p for x in ["nvidia","geforce","xx",'mx','quadro','m1200','p5000','p3000']):
        return "NVIDIA"
    elif "amd" in p or "ati" in p:
        return "AMD"
    elif "intel" in p or "core" in p or "hd" in p:
        return "Intel"
    elif any(x in p for x in ["qualcomm", "mali", "apple", "powervr", "rtx", "gtx"]):
        return "ARM SoC/Mobile"
    else:
        return "Unknown"

pc_df["GPU"] = pc_df["GPU"].apply(map_gpu)

In [49]:
# Check work
gpu_unique_values = pc_df['GPU'].unique()
print(f"There are {len(gpu_unique_values)} unique GPU values: {gpu_unique_values}")

There are 5 unique GPU values: ['Intel' 'Unknown' 'AMD' 'NVIDIA' 'ARM SoC/Mobile']

In [50]:
# Verify no missingness in GPU column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                   0.00
Ram Size                0.00
SSD Capacity            0.00
GPU                     0.00
Processor Speed        58.37
Type                   49.08
Release Year           87.32
Maximum Resolution     61.40
Model                  50.95
OS                     52.70
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note             0.00
Price                   0.00
dtype: float64

### Processor Speed Column

In [51]:
# get list of unique values for Processor Speed column
speed_unique_values = pc_df['Processor Speed'].unique()
print(f"There are {len(speed_unique_values)} unique Processor Speed values: {speed_unique_values}")

There are 195 unique Processor Speed values: ['Max up to 3.80 GHz' '4.20 GHz (1.90 GHz Base Frequency)' '2.40 GHz'
 'Minimum 1.40 GHz' '1.60 GHz' '1.00 GHz.4ghz' '2.80 GHz' '2.10 GHz'
 '1.70 GHz' nan '1.10 GHz' '3.80 GHz' '4.40 GHz' '2.30 GHz' '2.60 GHz'
 '1.90 GHz' 'Up to 4.2GHz' '3.10 GHz (2.50 GHz Base Frequnecy)'
 'up to 3.4Ghz' '2.50 GHz' 'up to 2.8GHZ' '3.50 GHz' '1.9 GHz'
 '2.8 to 3.9GHz' 'Up to 4.5GHz' '2.16 GHz' '2.4' '1.6 GHz' '2.5GHz'
 'Up to 4.20GHz' '1.73 GHz' '2.70 GHz' '1.80 GHz' '2.00 GHz' '2.20 GHz'
 '1.7 GHz' '2.48 GHz' '1.6GHz' '1.20 GHz' '1.1 GHz' '2.00-3.00GHz'
 '2.50GHz' '2.30GHz' '2.3GHz' '2.40GHz' 'Up to 4.40GHz' '3.10 GHz'
 '3.00-4.00GHz' '3.40GHz' '1.60GHz' '3.50GHz' '1.50 GHz' '2.60GHz'
 '1.30 GHz' '2.90 GHz' '3.00 GHz' '1.70GHz Up to 5.00GHz' '3.30 GHz'
 '1.50-1.99GHz' '2.90GHz' '2.80 GHz - 3.90 GHz' '2.20GHz' '2.26 MHz' 'na'
 '2.26ghz' '2.00 GHz.16ghz' '1.00-1.49GHz' '2.1 GHz' '1.9ghz' '1.00 GHz'
 '2.7ghz' '2.66 GHz' '2.67 GHz' '4.10 GHz' '1.40 GHz' '1.83 GHz'
 'Max Turbo Frequency @ 3.90 GHz' '4.70 GHz' '3GHz'
 '3.90 GHz (2.80 GHz Base Frequency)' '3.10 GHz (2.50 GHz Base Frequency)'
 '3.90 GHz' '1.9 GHz - 4.20 GHz' '3.00GHz' '1.00 GHz.83ghz' '5.10 ghz'
 '2.55 GHz' 'Up to 4.10 GHz' '3.40 GHz' '4.6 GHz' '3.60 GHz'
 '3.60 GHz (1.60 GHz Base Frequency)' '3.60 GHz (1.70 GHz Base Frequency)'
 'Up to 3.3GHz' '3.4 GHz (1.60 GHz Base Frequency)' '5.00 GHz'
 '3.40 GHz (1.60 GHz Base Frequnecy)' '3.70 GHz' '4.00 GHz'
 '4.90 GHz (1.80 GHz Base Frequency)' '2.80 - 4.70 GHz' 'Up to 4.80GHz'
 '1.07 GHz' '2.00GHz' 'Windows 10 Home (FREE Upgrade to Windows 11* )'
 '1.46 GHz' '1.66 GHz' '4.20 GHz' '1.70 GHz to 2.40GHz' 'up to 3.6Ghz'
 '2.4 GHz - 4.2 GHz' '2.26 GHz' '2.70GHz' 'up to 3.4ghz TURBO' '800 MHz'
 '1.10GHz' '1.20GHz' 'See Title/Description' '2.00 GHz.58ghz' '1.70GHz'
 'Up To 2.6GHz' '4.60 GHz' '2.00 GHz.1ghz' '2.5-3.1 GHZ'
 '2.00 GHz.00 Ghz.00 Ghz.16ghz' '2.1 GHZ' 'UP to 3.4Ghz' '3.3 GHz'
 '2.4 Ghz' '2.6GHz' 'I5-8350u @1.7GHz' '4.2 GHz' '1.70 GHz - 3.60 GHz'
 '4.80 GHz'
 '1.00 GHz.00 Ghz.00 Ghz.00 Ghz.00 Ghz.00 Ghz.00 Ghz.00 Ghz.00 Ghz.00 Ghz.4ghz'
 '3.40GHz (Max Turbo Speed: 3.80 GHz)' '4.7GHz' '3.90GHz' '2.5ghz'
 '3.20 Ghz' '1.80 TO 4.60GHZ' '3.20 GHz' '2.30Ghz' '2.4ghz' '1.44 GHz'
 '4.30 GHz' '1.86 GHz' '2.4GHz' '1.8GHz' '1.80 Ghz' '4.50 GHz'
 '1.1GHz-2.4Ghz' 'Up to 4.3GHz' '2.40 ghz' 'up to 2.80 GHz'
 'Up to 4.10GHz' '2.00 ghz or more' '2.08 GHz' '2.4 GHz' 'Various'
 '1.90GHz' '2.399GHz' '4.90 GHz'
 'Intel Core 13th Generation i5-1335U Processor (10 Core,  Up to 4.6'
 '2.5 GHZ' '1.1-2.8 GHz'
 'Intel Core 13th Generation i5-1335U Processor (10 Core, Up to 4.6'
 '4.7 GHz' '1.3GHz' '1.9 Ghz' '2.10GHz' '1.1GHz' '1.9GHz' '2.3' '2.53 GHz'
 '1.90GHz / 2.40GHz (with Turbo Boost)' '2.8GHz' '2.8GHz-3.8GHz'
 '2.00 GHz.17ghz' '1.23 GHz' 'Good' '1.80GHz' '2.30 GHz / 4.60 GHz'
 'Core 2 Duo Processor' '2.3ghz' 'i7-7Y75 Processor (up to 3.60GHz)'
 '2.4 GHZ' '5.2 GHz' '1.87 GHz' '3.20 GHz up to 4.70 GHz'
 '1.80 ghz or more' '2.60GHz - 4.60GHz' '2.40 GHz+' 'Up to 4.4GHz' '2 GHz']

In [52]:
# Since the goal of the analysis is to present to an Ebay executive,
#    and Processor and Processor Speed are closely related,
# I have decided to drop Processor Speed to reduce redundancy
#    and limit possibilities for collinearity
pc_df = pc_df.drop(columns = 'Processor Speed')

# Check work
pc_df.head(5)

,Item Number,Brand,Processor,Screen Size,Color,Ram Size,SSD Capacity,GPU,Type,Release Year,Maximum Resolution,Model,OS,Hard Drive Capacity,Storage Type,Features,Condition,Seller Note,Price
0,85264981001,Chuwi,Intel Other,14,Grayscale,8 GB,Unknown,Intel,Notebook/Laptop,2021,2160 x 1440,CoreBook X,Windows 11 Home,512 GB SSD,SSD (Solid State Drive),"Backlit Keyboard, Built-in Microphone, Built...","New: A brand-new, unused, unopened, undamaged ...",0,$303.68
1,85264981002,Dell,Intel Core,14,Grayscale,Unknown,Unknown,Intel,Notebook/Laptop,Refurbished in 2023,1920 x 1080,Dell Latitude 7490,Windows 11 Pro,2 TB,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - RefurbishedThe item shows minimal ...,1,$399.99 to $634.99
2,85264981003,Dell,Intel Core,14,Grayscale,16 GB,Unknown,Intel,Notebook/Laptop,2019,1920 x 1080,Dell Latitude E5470,Windows 10 Pro,500 GB,SSD (Solid State Drive),"10/100 LAN Card, Backlit Keyboard, Bluetooth, ...",UsedAn item that has been used previously. The...,1,$175.00
3,85264981004,HP,Intel Other,11,Grayscale,4 GB,Unknown,Intel,Notebook/Laptop,NaN,1366 x 768,HP Chromebook 11 G6,Chrome OS,16 GB,eMMC,"Bluetooth, Built-in Microphone, Built-in Webca...",Good - RefurbishedThe item shows moderate wear...,1,$84.99
4,85264981005,Dell,Intel Core,Various,Unknown,8 GB,256 GB,Unknown,Notebook/Laptop,2015,1366 x 768,Various Models,Windows 10,NO HDD,SSD (Solid State Drive),"10/100 LAN Card, Built-in Microphone, Built-in...",Good - RefurbishedThe item shows moderate wear...,1,$101.22

### Type Column

In [53]:
# get list of unique values for Type column
type_unique_values = pc_df['Type'].unique()
print(f"There are {len(type_unique_values)} unique Type values: {type_unique_values}")

There are 78 unique Type values: ['Notebook/Laptop' 'Laptop' 'Netbook' nan 'N/A, Notebook/Laptop'
 'Convertible 2-in-1 Laptop/Tablet' 'Notebook' 'Chromebook'
 'Ultra-mobile PC (UMPC)' 'NB' 'ThinkPad' 'Pc Portable'
 'Ordinateur portable/Pc portable' 'Tablette robuste'
 'ORDINATEUR PORTABLE' 'Gaming Laptop Computers' 'Windows Laptop' 'Tablet'
 'Wireless' 'Toughbook' '2-in-1 tablet laptop' 'Thinkpad' 'Ultrabook'
 'Laptop LCD Screen' 'NOTEBOOK' 'Panel PC' 'Loose Key(s)' 'Convertible'
 'Écran numériseur' 'Ordinateur portable convertible' 'Touchscreen laptop'
 'Ordinateur portable PC portable' 'LCD Display'
 'Convertible 2-In-1 Laptop/Tablet' 'Bureau' 'Notebook/Laptop/Tablet'
 'Laptop/Notebook' 'eBook Reader' 'Tablet Computer'
 'Notebook, ordinateur portable' 'Ultra Mobile PC (UMPC)'
 'Rugged Tough Tablet' 'Getac' 'Laptop/Tablet' 'Subnotebook/Ultraportable'
 'ChromeBook' 'Ultra Rugged Toughbook' '2-in-1 Convertible' 'Laptops'
 'Budget Laptops' 'Computers' '2 in 1 Laptop/Tablet' 'Workstation/Laptop'
 'Rugged Tablet' 'Tablet/Laptop Convertible' 'Desktop' 'laptop'
 'Macbook Pro' 'Power Adapter' 'Performance Base Keyboard'
 'CARDBUS ADAPTER' 'Toughbook ultra robuste' '2 IN 1 CHROMEBOOK'
 'WARRANTY: 90 DAYS. WARRANTY' 'Batterie' 'Mini Tower PC' 'Does not apply'
 'Tablet NoteBook' 'Gaming Laptop' 'Keyboard' 'toughpad' 'AWESOME'
 'Laptop/Portable Workstation' 'LCD Touchscreen Assembly' 'Durabook'
 'Rugged Tablet PC' 'Dell' 'SCSI cable']

In [54]:
# Create Tablet vs full Laptop categories, as well as 'Accessories' and "Unknown"
def map_type(type_pc):
    if pd.isna(type_pc):
        return "Unknown"
    p = str(type_pc).lower()

    # In looking at the unique values, there are a few broad categories that I
    #     think would be interesting to an Ebay exec.
    if any(x in p for x in ["na",'n/a','warranty','/','bureau','computers']):
        return "Unknown"
    elif any(x in p for x in ['keyboard','adapter','cable','batterie']):
        return "Accessory"
    elif any(x in p for x in ['ebook','tablet','touch']):
        return "Tablet"
    elif any(x in p for x in ['laptop','book','convertible','nb','pc','getac','thinkpad']):
        return "Laptop"
    else:
        return "Unknown"

pc_df["Type"] = pc_df["Type"].apply(map_type)

In [55]:
# Check work
type_unique_values = pc_df['Type'].unique()
print(f"There are {len(type_unique_values)} unique Type values: {type_unique_values}")

There are 4 unique Type values: ['Unknown' 'Laptop' 'Tablet' 'Accessory']

In [56]:
# Verify no missingness in GPU column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                   0.00
Ram Size                0.00
SSD Capacity            0.00
GPU                     0.00
Type                    0.00
Release Year           87.32
Maximum Resolution     61.40
Model                  50.95
OS                     52.70
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note             0.00
Price                   0.00
dtype: float64

### Release Year Column

In [57]:
# get list of unique values for Release Year column
year_unique_values = pc_df['Release Year'].unique()
print(f"There are {len(year_unique_values)} unique Year values: {year_unique_values}")

There are 39 unique Year values: ['2021' 'Refurbished in 2023' '2019' nan '2015' '2017' '2020' '2018'
 '2023' '2013' '2022' '2014' '2016' '2007' '2009' 'Acer Aspire V3-571G'
 '2010' '2012' '2022 (Refurbished)' '0' '2006' 'Various' '2008'
 'see manufacturer' 'na' '2023 Refurbished' '2020 (Refurbished By MAR)'
 'Cyrstal Clear Touchscreen' '2024 REFURBISH DATE' '2022 Refurbished'
 'Updated to 2023' 'N/a' '2005' '6/11/2021' 'Any' 'Unknown'
 'Seller Refurbished: 2022' 'Refurbished 2023' '2000']

In [58]:
# Since release years are at year 2000 or later, or an unknown value,
#    I have chosen to delete Release Year. Here, I assume most functional and not deprecated
#    computers used and sold on Ebay today are at least from year 2000, if not 2010
pc_df = pc_df.drop(columns = 'Release Year')

# Check work
pc_df.head(5)

,Item Number,Brand,Processor,Screen Size,Color,Ram Size,SSD Capacity,GPU,Type,Maximum Resolution,Model,OS,Hard Drive Capacity,Storage Type,Features,Condition,Seller Note,Price
0,85264981001,Chuwi,Intel Other,14,Grayscale,8 GB,Unknown,Intel,Unknown,2160 x 1440,CoreBook X,Windows 11 Home,512 GB SSD,SSD (Solid State Drive),"Backlit Keyboard, Built-in Microphone, Built...","New: A brand-new, unused, unopened, undamaged ...",0,$303.68
1,85264981002,Dell,Intel Core,14,Grayscale,Unknown,Unknown,Intel,Unknown,1920 x 1080,Dell Latitude 7490,Windows 11 Pro,2 TB,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - RefurbishedThe item shows minimal ...,1,$399.99 to $634.99
2,85264981003,Dell,Intel Core,14,Grayscale,16 GB,Unknown,Intel,Unknown,1920 x 1080,Dell Latitude E5470,Windows 10 Pro,500 GB,SSD (Solid State Drive),"10/100 LAN Card, Backlit Keyboard, Bluetooth, ...",UsedAn item that has been used previously. The...,1,$175.00
3,85264981004,HP,Intel Other,11,Grayscale,4 GB,Unknown,Intel,Unknown,1366 x 768,HP Chromebook 11 G6,Chrome OS,16 GB,eMMC,"Bluetooth, Built-in Microphone, Built-in Webca...",Good - RefurbishedThe item shows moderate wear...,1,$84.99
4,85264981005,Dell,Intel Core,Various,Unknown,8 GB,256 GB,Unknown,Unknown,1366 x 768,Various Models,Windows 10,NO HDD,SSD (Solid State Drive),"10/100 LAN Card, Built-in Microphone, Built-in...",Good - RefurbishedThe item shows moderate wear...,1,$101.22

### Maximum Resolution Column

In [59]:
# get list of unique values for Max Res column
max_res_unique_values = pc_df['Maximum Resolution'].unique()
print(f"There are {len(max_res_unique_values)} unique Max Resolution values: {max_res_unique_values}")

There are 79 unique Max Resolution values: ['2160 x 1440' '1920 x 1080' '1366 x 768' nan '2560 x 1600' '3000 x 2000'
 '2256 x 1504' '1366x768' '2736 x 1824' '1920 x 1200' '2560 x 1440' 'HD'
 '1280 x 800' 'Full HD' '1600 x 900' '1024 x 576' '3840 x 2160'
 '1366 x 768 (HD)' 'FHD (1920 x 1080)' '1920 x 1280' '1368x788' '2K'
 '1024 x 600' '1024 x 768' '2160 X1440' '2256x1504' '1920x1080'
 '1920×1080' '2880 x 1920' 'Full HD 1920 x 1080' '2200 x 1650' '2220x1080'
 '1900 x 1200' '1366 x 786' 'Full HD (1920 x 1080)' '3000 × 2000'
 '2560 x 1600 ( WQXGA )' '3456 x 2160' '1680 x 1050' '800 x 480'
 'High Quality' '1600x900' '1920 x 1080 (FHD)' '3840 x 2400'
 '1920 x 1080 ( Full HD )' 'See Title/Description' '1920 × 1200, 142 PPI'
 '1920 x 1080 Full HD' '1920 x 1080p' '3200 x 1800' '1800 x 1200'
 '3072 x 1920' '1028 x 800'
 '1366 x 768 pixels at 262 K colors HD WLED Anti-Glare' 'Like New'
 '1600X900' '1920x1200' '2880 x 1800' '1280 x 720' '1280 x 1024'
 '1360 x 768' '1920x1080 FHD' '1900x600' '1366 x 912' '2160 x 1350'
 '1920X1080' '1024 x 728' 'HD (1366 x 768)' 'Full HD (1920x1080p)'
 '1366X768 HD' 'ANY' '1440 x 900' '2560X1600' '1366 x 768 ( HD )'
 '1024 x 480' '2560x1600' '1536 x 2048' '3200x1800' '1920x1080 Full HD']

In [60]:
# Consult ChatGPT to help map low vs high resolution categories and understand what constitudes high vs low res
# Citation: ChatGPT. (2025, September 9). Conversation about sorting laptop screen resolution values into high and low categories, and creating a Python function for cleaning resolution data. OpenAI. Personal communication.

def map_resolution(res):
    if pd.isna(res):
        return "Unknown"
    s = str(res).lower().strip()

    # Regular HD is actually considered low resolution in the computer world
    if "hd" in s and not any(x in s for x in ["full", "fhd", "1920"]):
        return "Low"

    # These are considered high resolution keywords
    if any(x in s for x in ["full", "fhd", "2k", "4k", "uhd"]):
        return "High"

    # Extract numeric width × height values for comparison
    nums = re.findall(r"\d{3,4}", s)
    if len(nums) >= 2:
        width =int(nums[0])
        height = int(nums[1])
        # Rule: Full HD starts at 1920×1080
        if width >= 1920 and height >= 1080:
            return "High"
        else:
            return "Low"

    return "Unknown"

pc_df["Maximum Resolution"] = pc_df["Maximum Resolution"].apply(map_resolution)

In [61]:
# Rename column for clear understanding
pc_df = pc_df.rename(columns={'Maximum Resolution': 'Resolution'})

# Check work
max_res_unique_values = pc_df['Resolution'].unique()
print(f"There are {len(max_res_unique_values)} unique Resolution values: {max_res_unique_values}")

pc_df.head(3)

There are 3 unique Resolution values: ['High' 'Low' 'Unknown']

,Item Number,Brand,Processor,Screen Size,Color,Ram Size,SSD Capacity,GPU,Type,Resolution,Model,OS,Hard Drive Capacity,Storage Type,Features,Condition,Seller Note,Price
0,85264981001,Chuwi,Intel Other,14,Grayscale,8 GB,Unknown,Intel,Unknown,High,CoreBook X,Windows 11 Home,512 GB SSD,SSD (Solid State Drive),"Backlit Keyboard, Built-in Microphone, Built...","New: A brand-new, unused, unopened, undamaged ...",0,$303.68
1,85264981002,Dell,Intel Core,14,Grayscale,Unknown,Unknown,Intel,Unknown,High,Dell Latitude 7490,Windows 11 Pro,2 TB,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - RefurbishedThe item shows minimal ...,1,$399.99 to $634.99
2,85264981003,Dell,Intel Core,14,Grayscale,16 GB,Unknown,Intel,Unknown,High,Dell Latitude E5470,Windows 10 Pro,500 GB,SSD (Solid State Drive),"10/100 LAN Card, Backlit Keyboard, Bluetooth, ...",UsedAn item that has been used previously. The...,1,$175.00

In [62]:
# Verify no missingness in Resolution column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                   0.00
Ram Size                0.00
SSD Capacity            0.00
GPU                     0.00
Type                    0.00
Resolution              0.00
Model                  50.95
OS                     52.70
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note             0.00
Price                   0.00
dtype: float64

### Model Column

In [ ]:
# get list of unique values for Model column
model_unique_values = pc_df['Model'].unique()
print(f"There are {len(model_unique_values)} unique Model values: {model_unique_values}")

In [65]:
# Since there is so much variation in Model variable, and Model names directly
#    relate to and frequently include Brand name, I choose to drop the Model column;
#    it will not be informative for analysis given all our other variables' information

pc_df = pc_df.drop(columns = 'Model')

# Check work
pc_df.head(5)

,Item Number,Brand,Processor,Screen Size,Color,Ram Size,SSD Capacity,GPU,Type,Resolution,OS,Hard Drive Capacity,Storage Type,Features,Condition,Seller Note,Price
0,85264981001,Chuwi,Intel Other,14,Grayscale,8 GB,Unknown,Intel,Unknown,High,Windows 11 Home,512 GB SSD,SSD (Solid State Drive),"Backlit Keyboard, Built-in Microphone, Built...","New: A brand-new, unused, unopened, undamaged ...",0,$303.68
1,85264981002,Dell,Intel Core,14,Grayscale,Unknown,Unknown,Intel,Unknown,High,Windows 11 Pro,2 TB,SSD (Solid State Drive),"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - RefurbishedThe item shows minimal ...,1,$399.99 to $634.99
2,85264981003,Dell,Intel Core,14,Grayscale,16 GB,Unknown,Intel,Unknown,High,Windows 10 Pro,500 GB,SSD (Solid State Drive),"10/100 LAN Card, Backlit Keyboard, Bluetooth, ...",UsedAn item that has been used previously. The...,1,$175.00
3,85264981004,HP,Intel Other,11,Grayscale,4 GB,Unknown,Intel,Unknown,Low,Chrome OS,16 GB,eMMC,"Bluetooth, Built-in Microphone, Built-in Webca...",Good - RefurbishedThe item shows moderate wear...,1,$84.99
4,85264981005,Dell,Intel Core,Various,Unknown,8 GB,256 GB,Unknown,Unknown,Low,Windows 10,NO HDD,SSD (Solid State Drive),"10/100 LAN Card, Built-in Microphone, Built-in...",Good - RefurbishedThe item shows moderate wear...,1,$101.22

### OS Column

In [66]:
# Get list of unique values for OS column
os_unique_values = pc_df['OS'].unique()
print(f"There are {len(os_unique_values)} unique OS values: {os_unique_values}")

There are 78 unique OS values: ['Windows 11 Home' 'Windows 11 Pro' 'Windows 10 Pro' 'Chrome OS'
 'Windows 10' 'win 11 pro' nan 'Not Included' 'FreeDOS' 'Windows 10 Home'
 'Windows Home 11' 'Windows Pro' 'No Os' 'Linux' 'Windows 10 Pros'
 'Ubuntu' 'Windows 11 Home S' '\u200eWindows 11 Home' 'Windows 11 pros'
 'Professional, Windows 10' 'Windows 10 pros' 'Windows' 'Windows 11'
 'Windows 7' 'i5-8265u' 'Android' 'ANDROID' 'Windows 10 Pro 64Bit'
 'Windows 7 Professional' 'macOS Ventura' 'Windows XP' 'No OS'
 'windows 11' 'Win 10' 'Microsoft Windows 7 Professionnal'
 'Windows 10/11 Pro' 'Windows 10 professionals'
 'Professional, Windows 10 Pro' 'Windows 8.1' 'macOS Big Sur'
 'Windows XP 64 Bit' 'Windows11 Pro' 'Android 4.4.4' 'Win 10 Pro 64'
 'Chrome' 'Not included' 'Windows 8.1, Windows 7' 'Google Chrome OS'
 'Window 10 Pro Not Activated' 'Windows 10 Professional'
 'Windows 10 Home 64' 'Windows 10 S' 'macOS' 'Kali'
 'Windows XP / Windows 7 Pro / Windows 10 Pro' 'Home, Windows 10'
 'Windows Vista' 'Windows 7 Pro 64BIT' 'Windows 11 S mode'
 'Windows 11 S Mode' 'Windows 10 Pro Academic'
 'Microsoft Windows 10 Professional' 'Window 11 Pro' 'linux Mint' 'Mac Os'
 'Windows10' 'MacOS' 'Microsoft Windows 11' 'Ubuntu/Linux+2nd OS' 'Pop OS'
 'Mac OS' 'Windows 10 Home in S Mode' 'Windows 10 pers'
 'Windows XP Professional Sp3' 'Windows 7 Professional, Windows 10'
 'Windows 11 Homex64' 'Win 10 Pro' 'Windows Vista Home Premium']

In [67]:
def map_os(os):
    if pd.isna(os):
        return "Unknown"
    p = str(os).lower()

    # Map recognized OS categories
    if 'win' in p:
        return "Windows"
    elif 'mac' in p:
        return "Mac"
    elif 'linux' in p or 'ubuntu' in p or 'kali' in p or 'pop' in p:
        return "Linux"
    elif 'chrome' in p:
        return "Chrome"
    elif 'free' in p or 'android' in p:
        return "Open Source"
    else:
        return "Unknown"

pc_df["OS"] = pc_df["OS"].apply(map_os)

In [68]:
# Check work
os_unique_values = pc_df['OS'].unique()
print(f"There are {len(os_unique_values)} unique OS values: {os_unique_values}")

There are 6 unique OS values: ['Windows' 'Chrome' 'Unknown' 'Open Source' 'Linux' 'Mac']

In [69]:
# Verify no missingness in OS column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                   0.00
Ram Size                0.00
SSD Capacity            0.00
GPU                     0.00
Type                    0.00
Resolution              0.00
OS                      0.00
Hard Drive Capacity    63.96
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note             0.00
Price                   0.00
dtype: float64

### Hard Drive Capacity Column

In [70]:
# get list of unique values for Hard Drive Capacity column
hdd_unique_values = pc_df['Hard Drive Capacity'].unique()
print(f"There are {len(hdd_unique_values)} unique HDD values: {hdd_unique_values}")

There are 114 unique HDD values: ['512 GB SSD' '2 TB' '500 GB' '16 GB' 'NO HDD' nan '16GB' '512 GB'
 '256 GB' '128 GB' '1 TB' 'Up to 2TB' '512GB SSD' '12 GB' '8 GB' '320 GB'
 'No HDD' 'Not Included' '180 GB' '32 GB' 'NO' 'No' '128GB' '160 GB'
 '64 GB' '500GB' '240 GB' '200 GB' 'SSD' '80GB-100 GB' '300 GB' '1tb'
 '1TB' '0' '160GB' '4 GB' '750 GB' '400GB' '250 GB' '1 GB'
 '120GB 240GB 512GB 1TB SELECT FROM ABOVE' '2 GB' '64gb' '720 GB'
 '128GB,  256GB,  500GB,  1TB,  2TB'
 '512 GB NVMe M.2 SSD Solid State Drive' '64GB' '1TB SSD'
 '1 TB SSD Solid State Drive' 'Not Applicable' '512gb' 'Up to 1 TB'
 'SSD ONLY' '32GB' '120 GB' '0 GB' 'SEE SSD' '80GB' '4 TB' '3500.16 GB'
 'up to 1 TB' '256GB/512GB/1TB SSD (as selected)'
 '256GB - 500GB - 1TB - 2TB' '2 TB SSD Solid State Drive' '80 GB'
 '64GB eMMC' '256 GB SSD' '256 GBSSD' '512 GB SSD Solid State Drive'
 '128 SSD' '2TB m.2 NvMe SSD' '16 GB SSD' '512GB' '640 GB' 'non' 'N/a'
 '3 GB' 'not included' '20 GB' '800 GB' '256 GB 512 GB 1TB 2TB' '465 GB'
 '256GB' 'SSD only' '2TB' '81GB' '256gb' '1' '256 GB 512 GB 1 TB 2 TB'
 '512' '500GB Solid State Hybrid Drive' 'Up to 2 TB' 'SSD Only' '320GB'
 '128 GB (gigabyte)' '250 GB or More' '1tb nvme' '0GB' '250 GB - 1 TB'
 'Non' '500 GB Large storage memory' '128 GB 256 GB 512 GB 1TB 2TB'
 '24 GB' '500 GB 1 TB 2 TB' '.' 'Not included' 'N.A.' '6 GB' "Don't Apply"
 '64GB SSD' '62 GB' '120 GB or More' '320 GB- 500 GB' '250 GB- 1 TB']

In [71]:
# Standardize and group HDD Capacity with help from ChatGPT
# Citation: Citation: ChatGPT. (2025, September 9). Conversation about sorting laptop HDD capacity, and creating a Python function for cleaning HDD data. OpenAI. Personal communication.

def map_storage(value):
    if pd.isna(value):
        return "Unknown"
    s = str(value).lower().strip()

    # No Storage
    if any(x in s for x in ["no hdd", "no", "not included", "not applicable", "n.a.", 
        "n/a", "none", "non", "0", "don't apply", "ssd only", "see ssd", "."]):
        return "No Storage"

    # Find all numbers in each value, and label those without numbers as unknown
    nums = re.findall(r"\d+\.?\d*", s)
    if not nums:
        return "Unknown"

    # Catch the values without digits
    try:
        size = float(nums[0])
    except:
        return "Unknown"

    # Convert TB to GB for grouping
    if "tb" in s:
        size_gb = size * 1000
    else:
        size_gb = size

    # Categorize
    if size_gb < 128:
        return "Small (<128 GB)"
    elif 128 <= size_gb <= 512:
        return "Standard (128–512 GB)"
    elif size_gb > 512:
        return "Large (≥1 TB)"
    else:
        return "Unknown"

pc_df["Hard Drive Capacity"] = pc_df["Hard Drive Capacity"].apply(map_storage)

In [72]:
# Check work
hdd_unique_values = pc_df['Hard Drive Capacity'].unique()
print(f"There are {len(hdd_unique_values)} unique HDD values: {hdd_unique_values}")

There are 5 unique HDD values: ['Standard (128–512 GB)' 'Large (≥1 TB)' 'No Storage' 'Small (<128 GB)'
 'Unknown']

In [73]:
# Verify no missingness in HDD column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                   0.00
Ram Size                0.00
SSD Capacity            0.00
GPU                     0.00
Type                    0.00
Resolution              0.00
OS                      0.00
Hard Drive Capacity     0.00
Storage Type           62.60
Features               61.00
Condition               9.43
Seller Note             0.00
Price                   0.00
dtype: float64

### Storage Type Column

In [74]:
# get list of unique values for Hard Drive Capacity column
storage_type_unique_values = pc_df['Storage Type'].unique()
print(f"There are {len(storage_type_unique_values)} unique Storage Type values: {storage_type_unique_values}")

There are 45 unique Storage Type values: ['SSD (Solid State Drive)' 'eMMC' nan 'HDD + SSD' 'HDD (Hard Disk Drive)'
 'Not Included' 'SSD' 'SSD (Condition solid)'
 'UFS (Universal Flash Storage)' 'ssd' 'na' 'Hard Drive' 'M.2' 'HDD'
 'NVME/HDD' 'NVMe' 'M.2 SOLID STATE' 'SSD + eMMC' 'eMMC Solid State SSD'
 'Touchscreen' 'M.2 NVMe' 'HDD/SSD' 'See Title/Description' '256GBSSD'
 '256 G' 'eUFS (embedded Universal Flash Storage)' 'other'
 'NVME M.2 SSD (Solid State Drive)' 'NVMe (Non-Volatile Memory Express)'
 'Solid State Drive (SSD)' 'SSD or SSD' '.' 'SSHD'
 '50GB SSHD (Solid State Hybrid Drive)'
 'SSD (Solid State Drive), HDD + SSD' 'Solid State Drive' 'HDD / SSD'
 'Nvme SSD' 'Flash Memory' 'SSHD (Solid State Hybrid Drive)' 'SSD + HDD'
 'N.A.' 'Not included' 'mSATA' 'NVMe m.2']

In [75]:
# Standardize and group Storage Type with help from ChatGPT
# Citation: ChatGPT. (2025, September 10). Conversation about cleaning and categorizing laptop storage type values (SSD, HDD, Hybrid, eMMC, UFS) using Python functions. OpenAI. Personal communication.

def map_storage_type(x):
    if pd.isna(x):
        return "Unknown"
    s = str(x).strip().lower()

    # Both SSD and HDD
    if ("hdd" in s and "ssd" in s) or "sshd" in s:
        return "Hybrid (SSD+HDD/SSHD)"

    # Only HDD
    if any(k in s for k in ["hdd", "hard drive"]) and "ssd" not in s:
        return "HDD"

    # Flash (embedded) – eMMC / UFS
    if any(k in s for k in ["emmc", "ufs", "eufs", "flash memory"]):
        return "Flash (eMMC/UFS)"

    # SSD only
    if any(k in s for k in ["ssd", "nvme", "m.2", "msata", "solid state"]):
        return "SSD"

    return "Unknown"

pc_df["Storage Type"] = pc_df["Storage Type"].apply(map_storage_type)

In [76]:
# Check work
storage_type_unique_values = pc_df['Storage Type'].unique()
print(f"There are {len(storage_type_unique_values)} unique Storage Type values: {storage_type_unique_values}")

There are 5 unique Storage Type values: ['SSD' 'Flash (eMMC/UFS)' 'Unknown' 'Hybrid (SSD+HDD/SSHD)' 'HDD']

In [77]:
# Verify no missingness in HDD column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number             0.00
Brand                   0.00
Processor               0.00
Screen Size             0.00
Color                   0.00
Ram Size                0.00
SSD Capacity            0.00
GPU                     0.00
Type                    0.00
Resolution              0.00
OS                      0.00
Hard Drive Capacity     0.00
Storage Type            0.00
Features               61.00
Condition               9.43
Seller Note             0.00
Price                   0.00
dtype: float64

### Features Column

In [78]:
# get list of unique values for Features column
feat_unique_values = pc_df['Features'].unique()
print(f"There are {len(feat_unique_values)} unique Features values: {feat_unique_values}")

There are 710 unique Features values: ['Backlit Keyboard,  Built-in Microphone,  Built-in Webcam'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, LTE, Multi-Touch Trackpad, Widescreen Display, Wi-Fi'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Touchscreen, Widescreen Display, Wi-Fi'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Widescreen Display, Wi-Fi'
 '10/100 LAN Card, Built-in Microphone, Built-in Webcam, Wi-Fi'
 'Touchscreen, Bluetooth' 'Bluetooth, Built-in Webcam' nan 'Wi-Fi'
 'Touchscreen, Bluetooth, Built-in Webcam, Wi-Fi, Backlit Keyboard, Built-in Microphone'
 'Built-in Microphone,  Built-in Webcam' 'Bluetooth'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Wi-Fi'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Convertible 2-in-1 Laptop/Tablet, Touchscreen, Wi-Fi'
 'Backlit Keyboard, Bluetooth, Built-in Webcam, Touchscreen, Wi-Fi'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Convertible 2-in-1 Laptop/Tablet, Touchscreen'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Multi-Touch Trackpad,  Wi-Fi'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Widescreen Display, Wi-Fi'
 '3D Camera,  Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Wi-Fi'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Touchscreen'
 'Touchscreen, Bluetooth, Built-in Webcam, Wi-Fi, Multi-Touch Trackpad, Rugged, Built-in Microphone'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Wi-Fi, USB 3.2, Ethernet, Media card reader, USB-C'
 'Built-in Microphone,  Built-in Webcam,  Bluetooth,  Wi-Fi'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Multi-Touch Trackpad,  Widescreen Display,  Wi-Fi'
 '10/100 LAN Card, Bluetooth, Built-in Microphone, Built-in Webcam, Force Touch Trackpad, Multi-Touch Trackpad, Touchscreen, Wi-Fi'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Optical Drive, Wi-Fi'
 'Bluetooth, Backlit Keyboard, Built-in Microphone, Built-in Webcam, Wi-Fi'
 'Bluetooth, Wi-Fi' 'Touchscreen' 'Backlit Keyboard, Built-in Webcam'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Widescreen Display,  Wi-Fi,  Anti-glare HD LED Display,  WLED Backlight'
 'Bluetooth, Built-in Webcam, Convertible 2-in-1 Laptop/Tablet'
 'Built-in Microphone, Built-in Webcam, Convertible 2-in-1 Laptop/Tablet, Stylus, Touchscreen'
 'Bluetooth, Wi-Fi, MaxxAudio Pro, Media Card Reader, Wi-Fi 5, USB-C 3.2'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Rugged,  Stylus,  Touchscreen,  Wi-Fi,  Wifi'
 'Bluetooth,  Built-in Webcam,  Optical Drive,  Wi-Fi'
 'Bluetooth,  Built-in Webcam,  Wi-Fi,  Built-in Microphone'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Touchscreen,  Wi-Fi,  Widescreen Display'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Wi-Fi'
 'Touchscreen, Bluetooth, Built-in Webcam, Wi-Fi, 10/100 LAN Card, Backlit Keyboard, Force Touch Trackpad, Built-in Microphone'
 'Touchscreen, Bluetooth, Built-in Microphone, Built-in Webcam'
 'Multi-Touch Trackpad, Built-in Microphone, Backlit Keyboard, Bluetooth, Touchscreen, Wi-Fi, Convertible 2-in-1 Laptop/Tablet, Built-in Webcam, Force Touch Trackpad'
 '10/100 LAN Card, Bluetooth, Built-in Microphone, Built-in Webcam, Wi-Fi'
 'Touchscreen, Widescreen Display, Wi-Fi'
 '10/100 LAN Card,  Built-in Webcam,  Wi-Fi'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Wi-Fi'
 '5G,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Multi-Touch Trackpad,  Touchscreen,  Wi-Fi,  Dual Speakers'
 'Touchscreen, Bluetooth, Built-in Webcam, Wi-Fi'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Rugged, Touchscreen, Wi-Fi'
 'Touchscreen, Bluetooth, Built-in Webcam, Wi-Fi, Built-in Microphone'
 'Backlit Keyboard'
 'Backlit Keyboard,  Bluetooth,  Built-in Webcam,  Wi-Fi'
 'Backlit Keyboard, Bluetooth, Built-in Webcam, Multi-Touch Trackpad'
 '10/100 LAN Card,  Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Convertible 2-in-1 Laptop/Tablet,  Force Touch Trackpad,  LTE,  Rugged,  Stylus,  Touchscreen,  Wi-Fi'
 'Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Wi-Fi'
 '10/100 LAN Card,  Built-in Webcam'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Widescreen Display, Wi-Fi'
 'Wi-Fi, Bluetooth, Built-in Webcam, Multi-Touch Trackpad, Built-in Microphone, Backlit Keyboard'
 'Backlit Keyboard, Bluetooth, Built-in Webcam, Wi-Fi'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Convertible 2-in-1 Laptop/Tablet, Touchscreen, Wi-Fi'
 'Rugged, Wi-Fi'
 'Bluetooth, Built-in Webcam, Wi-Fi, Backlit Keyboard, Built-in Microphone'
 'Bluetooth, Built-in Webcam, Touchscreen'
 'Backlit Keyboard, Bluetooth, Built-in Webcam, Rugged, Touchscreen, Wi-Fi'
 'WiFi, AC Adapter, Built-in Microphone' 'Touchscreen, Backlit Keyboard'
 '10/100 LAN Card,  Wi-Fi,  SD Card Reader'
 'Touchscreen,  10/100 LAN Card,  Bluetooth,  LTE,  Backlit Keyboard,  Webcam integrated,  Wi-Fi'
 'Bluetooth, Built-in Webcam, Widescreen Display, Wi-Fi, Multi-Touch Trackpad, Built-in Microphone'
 'Rugged'
 'Bluetooth, Wi-Fi, Built-in Webcam, Touchscreen, Backlit Keyboard'
 'Bluetooth,  Built-in Webcam,  Built-in Microphone'
 '10/100 LAN Card,  Webcam integrated,  Wi-Fi,  Bluetooth'
 '10/100 LAN Card, Webcam integrated, Wi-Fi, Bluetooth'
 'Bluetooth, Built-in Webcam, Wi-Fi, Built-in Microphone'
 'Wi-Fi, Backlit Keyboard, Built-in Microphone, Built-in Webcam, Bluetooth'
 'Bluetooth, Wi-Fi, Convertible 2-in-1 Laptop/Tablet'
 '10/100 LAN Card,  Webcam integrated,  Wi-Fi,  Touchscreen,  Bluetooth'
 'Touchscreen, 10/100 LAN Card, Bluetooth, LTE, Backlit Keyboard, Webcam integrated, Wi-Fi'
 '10/100 LAN Card, Wi-Fi, SD Card Reader, Bluetooth'
 'Webcam integrated,  Wi-Fi,  Touchscreen,  Bluetooth'
 'Bluetooth, Built-in Webcam, Wi-Fi' 'Webcam integrated, Wi-Fi, Bluetooth'
 '10/100 LAN Card, Touchscreen, Wi-Fi, Bluetooth' 'Webcam integrated'
 '10/100 LAN Card, Wi-Fi, SD Card Reader'
 'Touch ID,  10/100 LAN Card,  Bluetooth,  Webcam integrated,  Wi-Fi,  Optical Drive'
 '10/100 LAN Card, Webcam integrated, Wi-Fi, Touchscreen, Bluetooth'
 '10/100 LAN Card,  Wi-Fi,  SD Card Reader,  Bluetooth'
 '10/100 LAN Card, Optical Drive, Wi-Fi, Bluetooth'
 'Numeric Keypad,  Audio by B&O,  Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam'
 'Convertible 2-in-1 Laptop/Tablet'
 'Touch ID,  10/100 LAN Card,  Wi-Fi,  Backlit Keyboard,  Bluetooth'
 '10/100 LAN Card, Wi-Fi'
 'Touch ID,  10/100 LAN Card,  Shockproof,  Bluetooth,  Webcam integrated,  Wi-Fi'
 'Display widescreen, Touch Bar, 10/100 LAN Card, Built-in Microphone, Bluetooth, 3D Camera, Webcam integrated, Wi-Fi'
 '10/100 LAN Card,  Wi-Fi'
 '10/100 LAN Card,  Optical Drive,  Wi-Fi,  Bluetooth'
 '10/100 LAN Card, Webcam integrated, Wi-Fi, Optical Drive, Bluetooth'
 'Built-in Webcam'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Wi-Fi'
 'Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Touchscreen,  Wi-Fi,  Fingerprint Reader'
 'Bluetooth, Wi-Fi, Touch ID' 'LTE'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Touchscreen, Wi-Fi'
 '10/100 LAN Card,  Backlit Keyboard,  Bluetooth,  Built-in Webcam,  Widescreen Display,  Wi-Fi'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Rugged'
 'Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Force Touch Trackpad,  Wi-Fi'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Touchscreen'
 'Bluetooth, Built-in Webcam, Wi-Fi, Spill-Resistant Keyboard, Backlit Keyboard, Touch ID'
 'GPS,  Fingerprint Reader,  Stylus,  Touchscreen,  Backlit Keyboard,  Rugged,  Detachable Keyboard,  RGB'
 'Built-in Webcam, Ambient Light Sensor, Backlit Keyboard, Built-in Microphone'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Touchscreen, Wi-Fi'
 'Touchscreen, Bluetooth, Built-in Webcam, Wi-Fi, Convertible 2-in-1 Laptop/Tablet'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Touchscreen,  Wifi 802.11AX,  USB 3.2'
 'Touch ID, Webcam integrated, Wi-Fi, Optical Drive, Bluetooth'
 'SIM slots,  Touchscreen,  Touch ID,  Bluetooth,  Webcam integrated,  Wi-Fi,  Player SD'
 'Touch ID, 10/100 LAN Card, Wi-Fi, Backlit Keyboard, Bluetooth'
 'Touch ID, 10/100 LAN Card, Bluetooth, Double battery, Webcam integrated, Wi-Fi'
 'Touch ID, 10/100 LAN Card, Shockproof, Bluetooth, Webcam integrated, Wi-Fi'
 'Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  LTE,  DVD'
 'Touchscreen,  Touch ID,  Shockproof,  Bluetooth,  Webcam integrated,  Wi-Fi,  Player SD'
 'Touchscreen, 10/100 LAN Card, Bluetooth, Double battery, Webcam integrated, Wi-Fi'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Convertible 2-in-1 Laptop/Tablet, Fingerprint Sensor, Multi-Touch Trackpad, Touchscreen, Wi-Fi'
 'Built-in Microphone, Webcam integrated, WIFI, Bluetooth'
 'Webcam integrated,  Wi-Fi,  Bluetooth'
 'SIM slots, Touchscreen, Touch ID, Bluetooth, Webcam integrated, Wi-Fi, Player SD'
 '10/100 LAN Card, Webcam integrated, Wi-Fi, Double battery, Bluetooth'
 'Backlit Keyboard, Bluetooth, Built-in Webcam'
 'Touchscreen, Bluetooth, Built-in Webcam, Convertible 2-in-1 Laptop/Tablet, Built-in Microphone'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Force Touch Trackpad, Wi-Fi'
 '10/100 LAN Card, Bluetooth, Built-in Microphone, Built-in Webcam, Optical Drive, Wi-Fi'
 '10/100 LAN Card, Bluetooth, Built-in Webcam'
 'Built-in Webcam,  Built-in Microphone'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Touchscreen,  Wi-Fi'
 'Bluetooth,  Built-in Webcam'
 'Backlit Keyboard, Bluetooth, Rugged, Touchscreen, Wi-Fi'
 'Bluetooth, Built-in Webcam, Widescreen Display, Wi-Fi, Backlit Keyboard, Force Touch Trackpad, Built-in Microphone'
 'Bluetooth,  Built-in Webcam,  Touchscreen,  Wi-Fi'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam'
 'Bluetooth, Built-in Microphone, Wi-Fi'
 '10/100 LAN Card,  Webcam integrated,  Wi-Fi,  Optical Drive,  Bluetooth'
 'Touch ID,  10/100 LAN Card,  Bluetooth,  Backlit Keyboard,  Webcam integrated,  Wi-Fi'
 'Built-in Webcam,  Wi-Fi,  Built-in Microphone,  Bluetooth'
 'Wi-Fi, Built-in Microphone'
 'Touchscreen,  Touch ID,  Bluetooth,  Backlit Keyboard,  MicroSD reader,  Webcam integrated,  Wi-Fi'
 '10/100 LAN Card,  Webcam integrated,  Wi-Fi,  Double battery,  Bluetooth'
 'Built-in Microphone, Built-in Webcam, Wi-Fi'
 'Backlit Keyboard,  Webcam integrated,  Wi-Fi,  Bluetooth'
 'Touch ID, 10/100 LAN Card, Shockproof, Bluetooth, Backlit Keyboard, Webcam integrated, Wi-Fi'
 'Touchscreen, Touch ID, Shockproof, Bluetooth, Webcam integrated, Wi-Fi, Player SD'
 'Touchscreen, Touch ID, Bluetooth, Backlit Keyboard, MicroSD reader, Webcam integrated, Wi-Fi'
 '10/100 LAN Card,  Touchscreen,  Wi-Fi,  Bluetooth'
 'Touchscreen,  10/100 LAN Card,  Bluetooth,  Backlit Keyboard,  Webcam integrated,  Wi-Fi'
 'Webcam integrated, Wi-Fi, Touchscreen, Bluetooth'
 'Webcam integrated, Wi-Fi, Player SD, Bluetooth'
 'Touch ID, 10/100 LAN Card, Bluetooth, Backlit Keyboard, Webcam integrated, Wi-Fi'
 'Touchscreen, 10/100 LAN Card, Bluetooth, Backlit Keyboard, Webcam integrated, Wi-Fi'
 'Webcam integrated,  Wi-Fi,  Water resistant,  Bluetooth'
 'Touch ID,  10/100 LAN Card,  Bluetooth,  Double battery,  Webcam integrated,  Wi-Fi'
 'Touch ID, 10/100 LAN Card, Bluetooth, Webcam integrated, Wi-Fi, Optical Drive'
 'FHD,  Touchscreen,  Wi-Fi,  Webcam integrated,  Bluetooth'
 'Webcam integrated, Wi-Fi, Water resistant, Bluetooth' 'Refurbished'
 'Built-in Microphone, Built-in Webcam, WIFI, Bluetooth'
 'Webcam integrated,  Wi-Fi,  Player SD,  Bluetooth'
 'Bluetooth, Built-in Webcam, Wi-Fi, 10/100 LAN Card, Backlit Keyboard, Built-in Microphone'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Touchscreen, Widescreen Display, Wi-Fi'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Force Touch Trackpad,  Multi-Touch Trackpad,  Widescreen Display,  Wi-Fi'
 '10/100 LAN Card, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Optical Drive, Rugged, Wi-Fi'
 'Touchscreen, Eye Tracking, Bluetooth, Built-in Webcam, Widescreen Display, Wi-Fi, Multi-Touch Trackpad, Convertible 2-in-1 Laptop/Tablet, Backlit Keyboard, Built-in Microphone'
 '10/100 LAN Card,  Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam'
 'Touchscreen, Bluetooth, Built-in Webcam, Widescreen Display, Wi-Fi, Backlit Keyboard, Built-in Microphone'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Widescreen Display,  Wi-Fi'
 'Backlit Keyboard,  Bluetooth,  Built-in Webcam' 'Built-in Webcam, Wi-Fi'
 'Built-in Microphone,  Built-in Webcam,  Convertible 2-in-1 Laptop/Tablet,  Stylus,  Touchscreen'
 'Touchscreen,  Bluetooth,  Built-in Webcam,  Wi-Fi,  Multi-Touch Trackpad,  Backlit Keyboard,  Built-in Microphone'
 '10/100 LAN Card, Bluetooth'
 'Built-in Microphone,  Built-in Webcam,  Wi-Fi'
 'Backlit Keyboard,  Bluetooth,  Built-in Webcam,  Rugged,  Touchscreen,  Wi-Fi'
 'Bluetooth,  Optical Drive,  Widescreen Display,  Wi-Fi,  DVD-RW,  Stereo Speakers and Microphone'
 'Touchscreen, Shockproof, Bluetooth, LTE, Webcam integrated, Wi-Fi, Player SD'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Touch ID, Widescreen Display, Wi-Fi'
 'Bluetooth, Built-in Webcam, Wi-Fi, Webcam, Dual Wi-Fi, Mini HDMI'
 'Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Touchscreen,  Wi-Fi'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Webcam, Widescreen Display, Wi-Fi'
 'Built-in Webcam,  Wi-Fi'
 'Bluetooth,  Built-in Webcam,  Wi-Fi,  Spill-Resistant Keyboard,  Backlit Keyboard,  Touch ID'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Optical Drive,  Wi-Fi'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Touchscreen'
 '10/100 LAN Card,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Wi-Fi'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Wi-Fi'
 'Wi-Fi,  Built-in Microphone,  Built-in Webcam,  Force Touch Trackpad'
 'Touchscreen,  Widescreen Display,  Wi-Fi'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Widescreen Display, Wi-Fi'
 '10/100 LAN Card, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Force Touch Trackpad, Wi-Fi'
 '10/100 LAN Card,  Built-in Microphone,  Built-in Webcam,  Wi-Fi'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Touchscreen, Wi-Fi'
 'Built-in Camera (Front & Rear), SD Card Reader, Built-in Microphone, Touchscreen'
 'Built-in Microphone,  Built-in Webcam,  Optical Drive,  Wi-Fi,  Wireless,  DVD+/-RW'
 'Bluetooth, Built-in Webcam, Wi-Fi, Backlit Keyboard'
 'Bluetooth, Built-in Microphone, Built-in Webcam' 'Bluetooth, Wi-Fi, LTE'
 'Built-in Microphone,  Built-in Webcam,  Wireless'
 'Bluetooth, Built-in Webcam, 10/100 LAN Card, Backlit Keyboard'
 'Touchscreen, Bluetooth, Wi-Fi' 'Bluetooth,  Optical Drive,  Wi-Fi'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  LTE,  Touchscreen,  Wi-Fi'
 'Built-in Microphone,  Built-in Webcam,  Multi-Touch Trackpad,  Bluetooth 4.2,  802.11ac Wi-Fi'
 'Touchscreen, Bluetooth, Built-in Webcam, Widescreen Display, Wi-Fi, 10/100 LAN Card, Backlit Keyboard, Built-in Microphone'
 'Touchscreen, Bluetooth, Backlit Keyboard'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Wi-Fi'
 'Bluetooth,  Built-in Webcam,  WiFi,  Headphone Mic Combo Jack'
 'Touchscreen, Bluetooth, Built-in Webcam, Backlit Keyboard'
 'Wi-Fi,  Rugged'
 'Touchscreen,  Built-in Webcam,  Wi-Fi,  Built-in Microphone'
 'Backlit Keyboard, Bluetooth, Built-in Webcam, Touch ID, Wi-Fi'
 'Webcam, Bluetooth, Wi-Fi, Bluetooth, Wi-Fi'
 'Bluetooth, Built-in Webcam, Wi-Fi, Multi-Touch Trackpad, Backlit Keyboard, Built-in Microphone'
 'Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  FHD 1080P,  Nvidia Quadro M1200'
 'Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Convertible 2-in-1 Laptop/Tablet,  Touchscreen,  Wi-Fi,  Fingerprint Reader,  Webcam Kill Switch'
 '100/1000GB LAN Card, Dell Docking Station Port, 802.11ac Wi-Fi, Bluetooth 4.2, HD Matte 14" Display, 10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Widescreen Display, Wi-Fi'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Wi-Fi'
 'Bluetooth, Built-in Webcam, Backlit Keyboard'
 'Bluetooth,  Stylus,  Touchscreen,  Wi-Fi' 'Webcam, Bluetooth, Wi-Fi'
 'Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Optical Drive,  Wi-Fi'
 '10/100 LAN Card,  Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Multi-Touch Trackpad,  Wi-Fi'
 'Touchscreen, Built-in Webcam, Bluetooth, Built-in Microphone'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, LTE, Multi-Touch Trackpad, Widescreen Display, Wi-Fi, SIM Card Slot'
 'Bluetooth, Built-in Webcam, Optical Drive, Wi-Fi'
 'Bluetooth,  Built-in Webcam,  Wi-Fi,  Multi-Touch Trackpad,  Backlit Keyboard,  Built-in Microphone'
 '10/100 LAN Card,  Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Widescreen Display,  Wi-Fi'
 'Backlit Keyboard,  Rugged'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Optane Memory, Touchscreen, Wi-Fi'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Optical Drive, Rugged, Wi-Fi'
 'Built-in Microphone,  Built-in Webcam,  Optical Drive,  Wi-Fi'
 '10/100 LAN Card,  Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Force Touch Trackpad,  Multi-Touch Trackpad,  Touch ID,  Widescreen Display,  Wi-Fi'
 'Built-in Webcam, Built-in Microphone'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Convertible 2-in-1 Laptop/Tablet, Force Touch Trackpad, Rugged'
 'Backlit Keyboard, Built-in Webcam, Wi-Fi'
 'WiFi,  Headphone Mic Combo Jack,  Bluetooth,  Built-in Webcam'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Touch Bar, Wi-Fi'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Rugged,  Stylus,  Touchscreen,  Wi-Fi'
 'Backlit Keyboard,  Bluetooth,  Built-in Microphone,  Built-in Webcam,  Touchscreen,  Wi-Fi,  IR Camera for Hello Windows Feature,  Fingerprint Reader,  Bang & Olufsen Audio,  Stereo Speakers,  Smart Card Reader,  720p Webcam,  Full HD WLED backlight Display'
 '10/100 LAN Card, Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Optical Drive, Wi-Fi'
 'Built-in Microphone'
 'Backlit Keyboard, Bluetooth, Built-in Microphone, Built-in Webcam, Convertible 2-in-1 Laptop/Tablet, Touchscreen, Wi-Fi, Fingerprint Reader, Webcam Kill Switch'
 'Bluetooth,  Built-in Microphone,  Built-in Webcam,  Convertible 2-in-1 Laptop/Tablet,  Wi-Fi'
 'Widescreen Display, Backlit Keyboard, Touchscreen, Convertible 2-in-1 Laptop/Tablet, Multi-Touch Trackpad, Bluetooth, Built-in Microphone, 10/100 LAN Card, Touch ID, Built-in Webcam, Wi-Fi'
 'Backlit Keyboard, Multi-Touch Trackpad, Optical Drive, Widescreen Display, Wi-Fi'
 'Wi-Fi,Bluetooth,Built-in Webcam,Built-in Microphone'
 'Wi-Fi, Foreign Keyboard' 'Webcam,  Bluetooth,  Wi-Fi'
 'Bluetooth, Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, Wi-Fi'
 'Built-in Microphone, Built-in Webcam, Multi-Touch Trackpad, 802.11ac Wi-Fi, Bluetooth 4.2'
 'Built-in Microphone, Wi-Fi, Built-in Webcam, Bluetooth'

In [79]:
# Since feature lists are all different, there may be some interest in analyzing in regards to 
# whether there exists a note on which features the PC has.
# Therefore, I chose to assign 0 to any missing values, and 1 to any full values

def map_feat(feature):
    if pd.isna(feature):
        return 0
    else:
        return 1

pc_df["Features"] = pc_df["Features"].apply(map_feat)

In [80]:
# Check work
feat_unique_values = pc_df['Features'].unique()
print(f"There are {len(feat_unique_values)} unique Features values: {feat_unique_values}")

There are 2 unique Features values: [1 0]

In [81]:
# Verify no missingness in Features column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number            0.00
Brand                  0.00
Processor              0.00
Screen Size            0.00
Color                  0.00
Ram Size               0.00
SSD Capacity           0.00
GPU                    0.00
Type                   0.00
Resolution             0.00
OS                     0.00
Hard Drive Capacity    0.00
Storage Type           0.00
Features               0.00
Condition              9.43
Seller Note            0.00
Price                  0.00
dtype: float64

### Condition Column

In [82]:
# get list of unique values for Condition column
cdn_unique_values = pc_df['Condition'].unique()
print(f"There are {len(cdn_unique_values)} unique Condition values: {cdn_unique_values}")

There are 18 unique Condition values: ["New: A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is ...  Read moreabout the conditionNew: A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag. See the seller's listing for full details. See all condition definitionsopens in a new window or tab "
 "Very Good - RefurbishedThe item shows minimal wear and is backed by a one year warranty. It is fully functional and has been professionally refurbished,  inspected and cleaned to very good condition by qualified sellers. The item includes original or new accessories and will come in new generic packaging. See the seller's listing for full details. See all condition definitionsopens in a new window or tab"
 'UsedAn item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used. See the seller’s listing for full details and description of any imperfections. See all condition definitionsopens in a new window or tab'
 "Good - RefurbishedThe item shows moderate wear and is backed by a one year warranty. It is fully functional and has been professionally refurbished, inspected and cleaned to good condition by qualified sellers. The item includes original or new accessories and will come in a new generic packaging. See the seller's listing for full details. See all condition definitionsopens in a new window or tab"
 nan
 "Excellent - Refurbished: The item is in like-new condition, backed by a one year warranty. It has ...  Read moreabout the conditionExcellent - Refurbished: The item is in like-new condition, backed by a one year warranty. It has been professionally refurbished, inspected and cleaned to excellent condition by qualified sellers. The item includes original or new accessories and will come in new generic packaging. See the seller's listing for full details. See all condition definitionsopens in a new window or tab "
 "Open box: An item in excellent, new condition with no wear. The item may be missing the original ...  Read moreabout the conditionOpen box: An item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description. See all condition definitionsopens in a new window or tab "
 'Used: An item that has been used previously. The item may have some signs of cosmetic wear, but is ...  Read moreabout the conditionUsed: An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used. See the seller’s listing for full details and description of any imperfections. See all condition definitionsopens in a new window or tab '
 'For parts or not workingAn item that does not function as intended and is not fully operational. This includes items that are defective in ways that render them difficult to use, items that require service or repair, or items missing essential components. See the seller’s listing for full details. See all condition definitionsopens in a new window or tab'
 'For parts or not working: An item that does not function as intended and is not fully operational. ...  Read moreabout the conditionFor parts or not working: An item that does not function as intended and is not fully operational. This includes items that are defective in ways that render them difficult to use, items that require service or repair, or items missing essential components. See the seller’s listing for full details. See all condition definitionsopens in a new window or tab '
 "Very Good - Refurbished: The item shows minimal wear and is backed by a one year warranty. It is ...  Read moreabout the conditionVery Good - Refurbished: The item shows minimal wear and is backed by a one year warranty. It is fully functional and has been professionally refurbished,  inspected and cleaned to very good condition by qualified sellers. The item includes original or new accessories and will come in new generic packaging. See the seller's listing for full details. See all condition definitionsopens in a new window or tab "
 "Open boxAn item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description. See all condition definitionsopens in a new window or tab"
 "Excellent - RefurbishedThe item is in like-new condition, backed by a one year warranty. It has been professionally refurbished, inspected and cleaned to excellent condition by qualified sellers. The item includes original or new accessories and will come in new generic packaging. See the seller's listing for full details. See all condition definitionsopens in a new window or tab"
 "Good - Refurbished: The item shows moderate wear and is backed by a one year warranty. It is fully ...  Read moreabout the conditionGood - Refurbished: The item shows moderate wear and is backed by a one year warranty. It is fully functional and has been professionally refurbished, inspected and cleaned to good condition by qualified sellers. The item includes original or new accessories and will come in a new generic packaging. See the seller's listing for full details. See all condition definitionsopens in a new window or tab "
 'Seller refurbished: The item has been restored to working order by the eBay seller or a third party. ...  Read moreabout the conditionSeller refurbished: The item has been restored to working order by the eBay seller or a third party. This means the item was inspected, cleaned, and repaired to full working order and is in excellent condition. This item may or may not be in original packaging. See seller’s listing for full details. See all condition definitionsopens in a new window or tab '
 "Certified - Refurbished: The item is in pristine, like-new condition. It has been professionally ...  Read moreabout the conditionCertified - Refurbished: The item is in pristine, like-new condition. It has been professionally inspected, cleaned, and refurbished by the manufacturer or a manufacturer-approved vendor to meet manufacturer specifications. The item will be in new packaging with original or new accessories. See the seller's listing for full details. See all condition definitionsopens in a new window or tab "
 "Certified - RefurbishedThe item is in pristine, like-new condition. It has been professionally inspected, cleaned, and refurbished by the manufacturer or a manufacturer-approved vendor to meet manufacturer specifications. The item will be in new packaging with original or new accessories. See the seller's listing for full details. See all condition definitionsopens in a new window or tab"
 'Seller refurbishedThe item has been restored to working order by the eBay seller or a third party. This means the item was inspected, cleaned, and repaired to full working order and is in excellent condition. This item may or may not be in original packaging. See seller’s listing for full details. See all condition definitionsopens in a new window or tab']

In [83]:
def map_cdn(x):
    if pd.isna(x):
        return "Unknown"
    s = str(x).strip().lower()
    # Shorten condition string to simple overview
    s = s[:30]

    if "new" in s:
        return "New"
    elif 'excellent' in s:
        return 'Excellent'
    elif 'refurb' in s:
        return 'Excellent (Refurbished)'
    elif 'very good' in s:
        return "Very Good"
    elif 'good' in s:
        return "Good"
    elif 'used' in s:
        return 'Used'
    elif 'not working' in s:
        return 'Dysfunctional'

pc_df["Condition"] = pc_df["Condition"].apply(map_cdn)

In [84]:
# Check work
cdn_unique_values = pc_df['Condition'].unique()
print(f"There are {len(cdn_unique_values)} unique Condition values: {cdn_unique_values}")

There are 6 unique Condition values: ['New' 'Excellent (Refurbished)' 'Used' 'Unknown' 'Excellent'
 'Dysfunctional']

In [85]:
# Verify no missingness in Features column
missing_value_percentages = round(pc_df.isna().sum()/len(pc_df) * 100, 2)
print(missing_value_percentages)

Item Number            0.0
Brand                  0.0
Processor              0.0
Screen Size            0.0
Color                  0.0
Ram Size               0.0
SSD Capacity           0.0
GPU                    0.0
Type                   0.0
Resolution             0.0
OS                     0.0
Hard Drive Capacity    0.0
Storage Type           0.0
Features               0.0
Condition              0.0
Seller Note            0.0
Price                  0.0
dtype: float64

### Price Column

In [87]:
# get list of unique values for Price column
price_unique_values = pc_df['Price'].unique()
print(f"There are {len(price_unique_values)} unique Condition values: {price_unique_values}")

There are 2917 unique Condition values: ['$303.68 ' '$399.99 to $634.99' '$175.00 ' ... '$385.23 ' '$90.92 '
 '$567.74 ']

In [88]:
# There are too many unique prices to see individually, but we see some price ranges and 
# mostly properly formatted price in the head of the data
pc_df['Price'].head(30)

0               $303.68
1     $399.99 to $634.99
2               $175.00
3                $84.99
4               $101.22
5                $49.99
6                $39.59
7                $34.99
8               $279.99
9               $125.00
10              $138.00
11              $430.55
12               $69.99
13              $151.99
14              $243.99
15              $169.99
16              $218.00
17              $129.99
18               $39.99
19    $392.99 to $613.80
20              $625.00
21              $315.00
22              $199.99
23              $227.32
24              $299.99
25               $59.99
26               $44.99
27    $439.00 to $629.00
28    $206.65 to $315.42
29              $344.99
Name: Price, dtype: object

In [89]:
# Investigate ranges in the Price column
price_series = pd.Series(pc_df['Price'])
ranges=[]
for price in price_series:
    price.strip()
    if 'to' in price or '-' in price:
        ranges.append(price)

ranges.sort()
print(len(ranges))
print(ranges)

123
['$101.22 to $113.87', '$101.22 to $113.87', '$113.87 to $417.57', '$113.87 to $417.57', '$118.00 to $297.00', '$119.00 to $139.00', '$119.90 to $159.90', '$119.99 to $159.99', '$119.99 to $159.99', '$126.53 to $265.72', '$126.53 to $265.72', '$129.95 to $149.95', '$132.52 to $154.60', '$134.99 to $179.99', '$134.99 to $179.99', '$139.99 to $159.99', '$146.99 to $199.99', '$147.50 to $383.50', '$151.78 to $177.09', '$151.84 to $240.41', '$151.89 to $278.47', '$157.96 to $248.44', '$158.98 to $458.98', '$162.06 to $333.80', '$164.49 to $442.88', '$168.00 to $478.00', '$168.00 to $478.00', '$177.09 to $202.40', '$177.09 to $240.36', '$177.21 to $265.82', '$180.49 to $270.74', '$180.49 to $365.74', '$188.00 to $358.00', '$188.49 to $255.83', '$188.49 to $255.83', '$188.54 to $441.62', '$188.54 to $441.62', '$192.00 to $203.05', '$192.00 to $203.05', '$192.00 to $203.05', '$192.00 to $203.05', '$192.00 to $203.05', '$200.00 to $350.00', '$206.65 to $315.42', '$208.73 to $227.71', '$208.83 to $244.72', '$208.83 to $244.72', '$214.27 to $301.28', '$214.27 to $301.28', '$239.28 to $576.45', '$239.95 to $909.95', '$246.75 to $411.26', '$246.75 to $411.26', '$279.99 to $299.99', '$289.00 to $479.00', '$289.99 to $539.99', '$299.99 to $309.99', '$299.99 to $499.99', '$300.00 to $550.00', '$300.00 to $550.00', '$306.99 to $535.00', '$309.98 to $386.12', '$309.98 to $386.12', '$310.00 to $539.01', '$32.75 to $51.36', '$32.75 to $51.36', '$32.75 to $51.36', '$32.75 to $51.36', '$323.99 to $344.99', '$324.99 to $553.99', '$324.99 to $554.00', '$324.99 to $592.00', '$324.99 to $799.99', '$325.99 to $559.99', '$347.92 to $404.86', '$349.99 to $369.99', '$349.99 to $449.99', '$350.00 to $560.00', '$350.00 to $610.00', '$357.99 to $586.00', '$379.98 to $659.98', '$392.99 to $613.80', '$399.99 to $634.99', '$4.42 to $5.05', '$410.00 to $660.00', '$419.99 to $654.00', '$429.00 to $579.00', '$429.00 to $579.00', '$429.99 to $669.99', '$43.27 to $110.67', '$43.27 to $110.67', '$439.00 to $629.00', '$456.70 to $685.11', '$456.70 to $685.11', '$49.99 to $104.99', '$50.30 to $138.78', '$54.38 to $76.14', '$54.38 to $76.14', '$559.00 to $779.00', '$599.00 to $629.00', '$599.00 to $629.00', '$599.00 to $769.00', '$675.00 to $1,683.60', '$675.00 to $1,683.60', '$675.00 to $1,683.60', '$675.00 to $1,683.60', '$699.00 to $1,089.00', '$699.00 to $1,089.00', '$699.00 to $919.00', '$72.99 to $85.99', '$720.00 to $1,180.00', '$760.21 to $868.98', '$760.25 to $1,032.16', '$780.00 to $1,280.00', '$780.00 to $1,280.00', '$789.00 to $899.00', '$799.00 to $1,544.00', '$815.74 to $1,196.42', '$871.86 to $935.13', '$871.86 to $935.13', '$871.86 to $935.13', '$90.00 to $140.00', '$950.00 to $1,099.99']

In [90]:
def map_price(x):
    s = str(x)

    # If a range is present, keep the maximum dollar amount and delete the minimum
    #   Regardless, strip the $ and convert to float so this column can be used as
    #   a continuous variable in analysis
    # Here, I assume that laptop prices do not exceed $999,999
    if "to" in s:
        price_range = s.split("$")
        max_price = price_range[2]
        if ',' in max_price:
            split_max_price = max_price.split(',')
            max_price = split_max_price[0]+split_max_price[1]
        max_price = float(max_price)
        return max_price
    else:
        price = s.lstrip('$')
        if ',' in price:
            split_price = price.split(',')
            price = split_price[0]+split_price[1]
        price = float(price)
        return price

pc_df["Price"] = pc_df["Price"].apply(map_price)

In [91]:
# Check work
price_list = pd.Series(pc_df['Price']).tolist()
type(price_list[100])

float

### Item Number Column

In [99]:
# Drop Item Number column because it will not be informative for analysis
pc_df = pc_df.drop(columns = 'Item Number')

# Check work
pc_df.head(5)

,Brand,Processor,Screen Size,Color,Ram Size,SSD Capacity,GPU,Type,Resolution,OS,Hard Drive Capacity,Storage Type,Features,Condition,Seller Note,Price
0,Chuwi,Intel Other,14,Grayscale,8 GB,Unknown,Intel,Unknown,High,Windows,Standard (128–512 GB),SSD,1,New,0,303.68
1,Dell,Intel Core,14,Grayscale,Unknown,Unknown,Intel,Unknown,High,Windows,Large (≥1 TB),SSD,1,Excellent (Refurbished),1,634.99
2,Dell,Intel Core,14,Grayscale,16 GB,Unknown,Intel,Unknown,High,Windows,No Storage,SSD,1,Used,1,175.00
3,HP,Intel Other,11,Grayscale,4 GB,Unknown,Intel,Unknown,Low,Chrome,Small (<128 GB),Flash (eMMC/UFS),1,Excellent (Refurbished),1,84.99
4,Dell,Intel Core,Various,Unknown,8 GB,256 GB,Unknown,Unknown,Low,Windows,No Storage,SSD,1,Excellent (Refurbished),1,101.22

In [101]:
# Check final shape of our DataFrame before aggregating and removing duplicates
pc_df.shape
# I have limited the number of columns from 24 to 16 while maximizing the amount of rows available for analysis.

(6848, 16)

## Group and Aggregate Values to Validate Cleanliness of DataFrame

In [112]:
# Group records by Brand name
brand_groups = pc_df.groupby('Brand')
# Examine Brand counts
brand_groups['Brand'].agg(['count'])

                    count
Brand
Acer                  160
Alienware               6
Apple                  87
Asus                  114
Chuwi                  18
Compaq                  4
Craig                   1
Dell                 1361
Durabook                3
Fujitsu               159
Fusion5                 2
Gateway                21
Geo                     3
Getac                  20
GoldBook                1
Google                  7
HP                    524
Huawei                  9
Hyundai                 1
IBM                     3
Insignia                1
Intel                  15
Jumper                  1
Kano                    3
Kodak                  12
LG                    132
Lenovo                788
MSI                     9
Metabox                 1
Microsoft             134
Motion Computing        1
Mouse Computer          7
Olidata                 4
Packard Bell            3
Panasonic              62
Razer                   3
SGIN                   16
Samsung               122
Simpletek              35
Sony                   10
Toshiba                67
Uniwill                 3
Unknown              2910
VAIO                    2
Vulcan Electronics      2
Zebra                   1

In [105]:
# Group records by Processor
processor_groups = pc_df.groupby('Processor')
# Examine Processor counts
processor_groups['Processor'].agg(['count'])

             count
Processor
AMD Legacy      65
AMD Ryzen      101
ARM/Mobile      62
Apple            9
Intel Core    2585
Intel Other    609
Unknown       3417

In [111]:
# Rename screen size label for clear understanding of units
pc_df = pc_df.rename(columns={'Screen Size': 'Screen Size (in)'})
# Group records by Screen Size
ss_groups = pc_df.groupby('Screen Size (in)')
# Examine Processor counts
ss_groups['Screen Size (in)'].agg(['count'])

                  count
Screen Size (in)
10                   93
11                  336
12                  268
13                  389
14                 1495
15                  781
16                   58
7                   101
8                    16
9                     7
Unknown            3301
Various               3

In [114]:
# Group records by color
color_groups = pc_df.groupby('Color')
# Examine Type counts
color_groups['Color'].agg(['count'])

           count
Color
Grayscale   1839
Unknown     5009

In [115]:
# Group records by RAM 
ram_groups = pc_df.groupby('Ram Size')
# Examine Type counts
ram_groups['Ram Size'].agg(['count'])

          count
Ram Size
1 GB          8
12 GB        64
16 GB       669
2 GB         46
20 GB         5
24 GB         6
3 GB         11
32 GB       140
36 GB         1
4 GB        525
40 GB         4
6 GB         17
64 GB        27
8 GB        763
Unknown    4562

In [116]:
# Group records by SSD
ssd_groups = pc_df.groupby('SSD Capacity')
# Examine Type counts
ssd_groups['SSD Capacity'].agg(['count'])

              count
SSD Capacity
1 TB            160
128 GB          261
16 GB           150
2 TB             72
256 GB          696
32 GB           103
4 GB              3
4 TB             11
512 GB          475
64 GB            68
Unknown        4849

In [117]:
# Group records by GPU
gpu_groups = pc_df.groupby('GPU')
# Examine Type counts
gpu_groups['GPU'].agg(['count'])

                count
GPU
AMD               147
ARM SoC/Mobile     23
Intel            2731
NVIDIA            271
Unknown          3676

In [102]:
# Group records by Type
type_groups = pc_df.groupby('Type')
# Examine Type counts
type_groups['Type'].agg(['count'])

           count
Type
Accessory      8
Laptop       293
Tablet       167
Unknown     6380

In [118]:
# Group records by res
res_groups = pc_df.groupby('Resolution')
# Examine Type counts
res_groups['Resolution'].agg(['count'])

            count
Resolution
High         1380
Low          1252
Unknown      4216

In [119]:
# Group records by os
os_groups = pc_df.groupby('OS')
# Examine Type counts
os_groups['OS'].agg(['count'])

             count
OS
Chrome         339
Linux           27
Mac             13
Open Source     11
Unknown       3764
Windows       2694

In [120]:
# Group records by hdd
hdd_groups = pc_df.groupby('Hard Drive Capacity')
# Examine Type counts
hdd_groups['Hard Drive Capacity'].agg(['count'])

                       count
Hard Drive Capacity
Large (≥1 TB)            158
No Storage              1220
Small (<128 GB)          357
Standard (128–512 GB)    732
Unknown                 4381

In [121]:
# Group records by storage type
stor_groups = pc_df.groupby('Storage Type')
# Examine Type counts
stor_groups['Storage Type'].agg(['count'])

                       count
Storage Type
Flash (eMMC/UFS)         230
HDD                      232
Hybrid (SSD+HDD/SSHD)     38
SSD                     2035
Unknown                 4313

In [122]:
# Group records by feats
feat_groups = pc_df.groupby('Features')
# Examine Type counts
feat_groups['Features'].agg(['count'])

          count
Features
0          4177
1          2671

In [123]:
# Group records by condition
cdn_groups = pc_df.groupby('Condition')
# Examine Type counts
cdn_groups['Condition'].agg(['count'])

                         count
Condition
Dysfunctional              182
Excellent                  244
Excellent (Refurbished)    916
New                       1953
Unknown                    646
Used                      2907

In [124]:
# Group records by seller note
note_groups = pc_df.groupby('Seller Note')
note_groups['Seller Note'].agg(['count'])

             count
Seller Note
0             5272
1             1576

In [125]:
# Examine summary statistics of prices based on each operating system
os_groups['Price'].agg(['count','sum','mean','max','min'])

             count         sum        mean      max     min
OS
Chrome         339    32422.10   95.640413   798.89   16.00
Linux           27     5694.42  210.904444  2339.00   30.00
Mac             13     7112.34  547.103077   935.13  109.00
Open Source     11     2530.31  230.028182   687.06   10.49
Unknown       3764  1001670.11  266.118520  3860.29    5.42
Windows       2694  1085134.29  402.796693  3901.00    5.05

## Remove duplicates

In [126]:
# Check for duplicates
duplicates = pc_df.duplicated().sum() # boolean mask
duplicates

np.int64(2778)

In [129]:
# Remove duplicates and check work
pc_df_clean = pc_df.drop_duplicates()
len(pc_df_clean)
# Even after dropping duplicates, we keep more than 50% of our original data
# This will be helpful in providing detailed insights for an Ebay exec.

4070

In [128]:
# Export clean DataFrame to a CSV for sharing and future use
pc_df_clean.to_csv('EbayPcLaptopDataClean.csv')

## Discussion: Column Attributes Most Valuable to the Business

In [130]:
pc_df.head(2)

,Brand,Processor,Screen Size (in),Color,Ram Size,SSD Capacity,GPU,Type,Resolution,OS,Hard Drive Capacity,Storage Type,Features,Condition,Seller Note,Price
0,Chuwi,Intel Other,14,Grayscale,8 GB,Unknown,Intel,Unknown,High,Windows,Standard (128–512 GB),SSD,1,New,0,303.68
1,Dell,Intel Core,14,Grayscale,Unknown,Unknown,Intel,Unknown,High,Windows,Large (≥1 TB),SSD,1,Excellent (Refurbished),1,634.99

In [133]:
# An Ebay business executive will be most interested in how he will be making money and satisfying customers.

# General specs like Brand, Color, Type, OS, Features, Condition, Seller Note will be important in understanding 
#     the current supply and demand on Ebay's marketplace. This will be important to making money and drawing new
#     customer to Ebay: Who will Ebay market to next?

# More specific specs related to computer performance and quality will be helpful in understanding what is most valuable
#     to a customer. Those interested in larger storage space, high resolution, and efficient processors use a computer
#     differently than a casual laptop user. This will be important to attracting customers who are willing to pay higher
#     prices for a higher quality laptop, which means more money for the business.

# The columns previously dropped were not essential to understanding Ebay's customer base, supply, and demand.